const Icons = {
    app:          "cs-app-symbolic",
    mic:          "cs-mic-symbolic",
    speaker:      "cs-speaker-symbolic",
    volumeHigh:   "cs-volume-high-symbolic",
    volumeMedium: "cs-volume-medium-symbolic",
    volumeLow:    "cs-volume-low-symbolic",
    volumeMuted:  "cs-volume-muted-symbolic",
    user:         "cs-user-symbolic",
    battery:      "cs-battery-symbolic",
    bluetooth:    "cs-bluetooth-symbolic",
    info:         "cs-info-symbolic",
    key:          "cs-key-symbolic",
    filePen:      "cs-file-pen-symbolic",
    trash:        "cs-trash-symbolic",
    search:       "cs-search-symbolic",
    chevronRight: "cs-chevron-right-symbolic",
    chevronLeft:  "cs-chevron-left-symbolic",
    chevronUp:    "cs-chevron-up-symbolic",
    plus:         "cs-plus-symbolic",
    minus:        "cs-minus-symbolic",
    pause:        "cs-pause-symbolic",
    play:         "cs-play-symbolic",
    skipBack:     "cs-skip-back-symbolic",
    skipForward:  "cs-skip-forward-symbolic",
    wifiOff:      "cs-wifi-off-symbolic",
    bell:         "cs-bell-symbolic",
    bellOff:      "cs-bell-off-symbolic",
    check:        "cs-check-symbolic",
    menu:         "cs-menu-symbolic",
    settings:     "cs-settings-symbolic",
    terminal:     "cs-terminal-symbolic",
    grid:         "cs-grid-symbolic",
    sidebar:      "cs-sidebar-symbolic",
    close:        "cs-close-symbolic",
} as const

export default Icons
