import GObject from "gi://GObject"
import GLib from "gi://GLib"
import { execAsync } from "ags/process"

// Build a `hl.config({ input = { … } })` expression from a keyword-style option
// path ("input:touchpad:tap_to_click") + value, for `hyprctl eval`. String values
// are quoted; numbers/booleans pass through. The Lua parser rejects `hyprctl
// keyword`, so this is the only way to apply input options live.
function inputConfigEval(option: string, value: string | number): string {
    const path = option.replace(/^input:/, "").split(":")
    const lit = typeof value === "string" ? `"${value}"` : String(value)
    let inner = `${path[path.length - 1]} = ${lit}`
    for (let i = path.length - 2; i >= 0; i--) inner = `${path[i]} = { ${inner} }`
    return `hl.config({ input = { ${inner} } })`
}

class InputConfig extends GObject.Object {
    static {
        GObject.registerClass({
            GTypeName: "InputConfigManager",
            Signals: {
                changed: {},
            },
        }, this)
    }

    private _pointerSpeed = 0.0
    private _accelProfile = "adaptive"
    private _mouseNaturalScroll = false
    private _touchpadNaturalScroll = false
    private _touchpadTap = true
    private _numlockOnBoot = false
    private _kbLayout = "us"
    private _kbVariant = ""
    private _kbRepeatDelay = 600
    private _kbRepeatRate = 25

    private initialized = false

    constructor() {
        super()
        this.syncFromHyprland()
    }

    get pointerSpeed() { return this._pointerSpeed }
    get accelProfile() { return this._accelProfile }
    get mouseNaturalScroll() { return this._mouseNaturalScroll }
    get touchpadNaturalScroll() { return this._touchpadNaturalScroll }
    get touchpadTap() { return this._touchpadTap }
    get numlockOnBoot() { return this._numlockOnBoot }
    get kbLayout() { return this._kbLayout }
    get kbVariant() { return this._kbVariant }
    get kbRepeatDelay() { return this._kbRepeatDelay }
    get kbRepeatRate() { return this._kbRepeatRate }

    // Parse options directly from Hyprland live state
    private async syncFromHyprland() {
        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:sensitivity"])
            this._pointerSpeed = JSON.parse(out).float || 0.0
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:accel_profile"])
            const raw = JSON.parse(out).str || ""
            this._accelProfile = (raw === "" || raw === "[[EMPTY]]") ? "adaptive" : raw
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:natural_scroll"])
            this._mouseNaturalScroll = JSON.parse(out).int === 1
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:touchpad:natural_scroll"])
            this._touchpadNaturalScroll = JSON.parse(out).int === 1
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:touchpad:tap_to_click"])
            this._touchpadTap = JSON.parse(out).int === 1
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:numlock_by_default"])
            this._numlockOnBoot = JSON.parse(out).int === 1
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:kb_layout"])
            this._kbLayout = JSON.parse(out).str || "us"
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:kb_variant"])
            this._kbVariant = JSON.parse(out).str || ""
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:repeat_delay"])
            this._kbRepeatDelay = JSON.parse(out).int || 600
        } catch {}

        try {
            const out = await execAsync(["hyprctl", "getoption", "-j", "input:repeat_rate"])
            this._kbRepeatRate = JSON.parse(out).int || 25
        } catch {}

        this.initialized = true
        this.emit("changed")
    }

    private applyAndSave(option: string, value: string | number) {
        if (!this.initialized) return

        // 1. Live apply. The config uses Hyprland's Lua parser, which REJECTS
        // `hyprctl keyword` ("Use eval.") — so live changes go through `hyprctl
        // eval "hl.config({ input = { … } })"`.
        execAsync(["hyprctl", "eval", inputConfigEval(option, value)]).catch(console.error)

        // 2. Save to persistent UI-owned file
        const configPath = GLib.build_filenamev([GLib.get_home_dir(), ".config", "crystal-shell", "crystal-settings.lua"])

        // Build the contents of the UI-managed override file
        const contents = `\
-- CRYSTAL SHELL SETTINGS
-- Auto-generated by the Crystal Shell Settings UI. Do not edit manually.
hl.config({
    input = {
        sensitivity        = ${this._pointerSpeed.toFixed(2)},
        accel_profile      = "${this._accelProfile}",
        natural_scroll     = ${this._mouseNaturalScroll},
        numlock_by_default = ${this._numlockOnBoot},
        kb_layout          = "${this._kbLayout}",
        kb_variant         = "${this._kbVariant}",
        repeat_delay       = ${this._kbRepeatDelay},
        repeat_rate        = ${this._kbRepeatRate},
        touchpad = {
            natural_scroll   = ${this._touchpadNaturalScroll},
            tap_to_click = ${this._touchpadTap},
        },
    },
})`

        try {
            const targetDir = GLib.path_get_dirname(configPath)
            if (!GLib.file_test(targetDir, GLib.FileTest.EXISTS)) {
                GLib.mkdir_with_parents(targetDir, 0o755)
            }
            GLib.file_set_contents(configPath, contents)
        } catch (e) {
            console.error("Failed to write crystal settings:", e)
        }

        this.emit("changed")
    }

    setPointerSpeed(val: number) {
        this._pointerSpeed = val
        this.applyAndSave("input:sensitivity", val)
    }

    setAccelProfile(val: string) {
        this._accelProfile = val
        this.applyAndSave("input:accel_profile", val)
    }

    setMouseNaturalScroll(val: boolean) {
        this._mouseNaturalScroll = val
        this.applyAndSave("input:natural_scroll", val ? 1 : 0)
    }

    setTouchpadNaturalScroll(val: boolean) {
        this._touchpadNaturalScroll = val
        this.applyAndSave("input:touchpad:natural_scroll", val ? 1 : 0)
    }

    setTouchpadTap(val: boolean) {
        this._touchpadTap = val
        this.applyAndSave("input:touchpad:tap_to_click", val ? 1 : 0)
    }

    setNumlockOnBoot(val: boolean) {
        this._numlockOnBoot = val
        this.applyAndSave("input:numlock_by_default", val ? 1 : 0)
    }

    setKbRepeatDelay(val: number) {
        this._kbRepeatDelay = Math.round(val)
        this.applyAndSave("input:repeat_delay", this._kbRepeatDelay)
    }

    setKbRepeatRate(val: number) {
        this._kbRepeatRate = Math.round(val)
        this.applyAndSave("input:repeat_rate", this._kbRepeatRate)
    }

    setKbLayout(layout: string, variant = "") {
        this._kbLayout = layout
        this._kbVariant = variant
        execAsync(["hyprctl", "eval", `hl.config({ input = { kb_layout = "${layout}", kb_variant = "${variant}" } })`]).catch(console.error)
        this.applyAndSave("input:kb_layout", layout)
    }
}

const inputConfig = new InputConfig()
export default inputConfig
