import GObject from "gi://GObject"
import GLib from "gi://GLib"
import { execAsync } from "ags/process"

interface MonitorState {
    scale: number
    transform: number
}

class MonitorConfig extends GObject.Object {
    static {
        GObject.registerClass({ GTypeName: "MonitorConfigManager" }, this)
    }

    private state: Map<string, MonitorState> = new Map()
    private _vrr = 0

    /** Call once with the monitor list from AstalHyprland.get_monitors() */
    init(monitors: Array<{ name: string; scale?: number; transform?: number; vrr?: number }>) {
        this.state.clear()
        for (const mon of monitors) {
            this.state.set(mon.name, {
                scale: Math.round((mon.scale ?? 1.0) * 100) / 100,
                transform: mon.transform ?? 0,
            })
        }
        this._vrr = monitors[0]?.vrr ?? 0
    }

    getScale(name: string) { return this.state.get(name)?.scale ?? 1.0 }
    getTransform(name: string) { return this.state.get(name)?.transform ?? 0 }
    get vrr() { return this._vrr }

    setScale(name: string, scale: number) {
        const cfg = this.state.get(name) ?? { scale: 1.0, transform: 0 }
        cfg.scale = scale
        this.state.set(name, cfg)
        execAsync([
            "hyprctl", "keyword", "monitor",
            `${name},preferred,auto,${scale},transform,${cfg.transform}`,
        ]).catch(e => console.error("[MonitorConfig] scale:", e))
        this._save()
    }

    setTransform(name: string, transform: number) {
        const cfg = this.state.get(name) ?? { scale: 1.0, transform: 0 }
        cfg.transform = transform
        this.state.set(name, cfg)
        execAsync([
            "hyprctl", "keyword", "monitor",
            `${name},preferred,auto,${cfg.scale},transform,${transform}`,
        ]).catch(e => console.error("[MonitorConfig] transform:", e))
        this._save()
    }

    setVrr(val: number) {
        this._vrr = val
        execAsync(["hyprctl", "keyword", "misc:vrr", String(val)])
            .catch(e => console.error("[MonitorConfig] vrr:", e))
        this._save()
    }

    private _save() {
        const lines: string[] = [
            "# ── CRYSTAL SHELL MONITOR SETTINGS ─────────────────────────────────────────",
            "# Auto-generated by Crystal Shell Settings UI. Do not edit manually.",
            "",
        ]

        for (const [name, cfg] of this.state.entries()) {
            if (cfg.transform !== 0) {
                lines.push(`monitor = ${name}, preferred, auto, ${cfg.scale}, transform, ${cfg.transform}`)
            } else {
                lines.push(`monitor = ${name}, preferred, auto, ${cfg.scale}`)
            }
        }

        if (this._vrr !== 0) {
            lines.push("")
            lines.push("misc {")
            lines.push(`    vrr = ${this._vrr}`)
            lines.push("}")
        }

        const configPath = GLib.build_filenamev([
            GLib.get_home_dir(), ".config", "crystal-shell", "crystal-monitor.conf"
        ])
        try {
            const dir = GLib.path_get_dirname(configPath)
            if (!GLib.file_test(dir, GLib.FileTest.EXISTS)) {
                GLib.mkdir_with_parents(dir, 0o755)
            }
            GLib.file_set_contents(configPath, lines.join("\n") + "\n")
        } catch (e) {
            console.error("[MonitorConfig] Failed to write config:", e)
        }
    }
}

const monitorConfig = new MonitorConfig()
export default monitorConfig
