[preferred]
default=hyprland;gtk
org.freedesktop.impl.portal.ScreenCast=hyprland
org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.Settings=nidara;gtk
org.freedesktop.impl.portal.Wallpaper=nidara
org.freedesktop.impl.portal.DynamicLauncher=nidara
org.freedesktop.impl.portal.Account=nidara
org.freedesktop.impl.portal.Background=nidara
