// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/gen-widget-index.mjs — DO NOT EDIT.
// One file in widget/widgets/ = one registered widget. Regenerate with:
//   node scripts/gen-widget-index.mjs
// (also runs on npm run build/dev and before `ags run` in the dev launcher;
// the CI job "widgets-gen" fails if this committed file is stale.)
// ─────────────────────────────────────────────────────────────────────────────
import { AtomicWidget } from "../control-center/Types"
import battery from "./battery"
import bluetooth from "./bluetooth"
import brightness from "./brightness"
import calculator from "./calculator"
import clipboard from "./clipboard"
import cpuMemory from "./cpu-memory"
import darkMode from "./dark-mode"
import ethernet from "./ethernet"
import focus from "./focus"
import media from "./media"
import nightLight from "./night-light"
import screenrecord from "./screenrecord"
import screenshot from "./screenshot"
import volume from "./volume"
import vpn from "./vpn"
import wifi from "./wifi"

export const ALL_WIDGETS: AtomicWidget[] = [
    battery,
    bluetooth,
    brightness,
    calculator,
    clipboard,
    cpuMemory,
    darkMode,
    ethernet,
    focus,
    media,
    nightLight,
    screenrecord,
    screenshot,
    volume,
    vpn,
    wifi,
]
