-- ─────────────────────────────────────────────────────────────────────────────
-- Crystal Shell — Hyprland Lua configuration  (requires Hyprland ≥ 0.55)
-- Installed to /usr/share/crystal-shell/config/hypr/hyprland.lua
-- Do NOT edit this file directly. Use ~/.config/crystal-shell/hyprland-user.lua
-- for personal overrides (keyboard layout, monitors, startup apps, etc.)
-- ─────────────────────────────────────────────────────────────────────────────

-- Extend the Lua path so require() can find generated files in crystal-shell's
-- config directory (crystal-settings.lua, crystal-monitor.lua, hyprland-user.lua)
local home = os.getenv("HOME")
package.path = package.path
    .. ";" .. home .. "/.config/crystal-shell/?.lua"
    .. ";" .. home .. "/.config/hypr/?.lua"

-- Soft-load a module: missing files produce a notification, not a crash.
local function safe_require(mod)
    local ok, err = pcall(require, mod)
    if not ok then
        hl.notify("Crystal Shell: failed to load " .. mod .. ".lua\n" .. tostring(err), 8000)
    end
end


-- ── Monitor ───────────────────────────────────────────────────────────────────
-- Per-monitor overrides live in crystal-monitor.lua (sourced at the bottom).
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })


-- ── Look & feel ───────────────────────────────────────────────────────────────
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 8,
        border_size = 1,
        col = {
            active_border   = { colors = {"rgba(ffffff4d)", "rgba(ffffff1a)"}, angle = 45 },
            inactive_border = "rgba(59595933)",
        },
        layout           = "dwindle",
        resize_on_border = true,
        allow_tearing    = true,
    },

    decoration = {
        rounding       = 24,
        rounding_power = 3.2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        blur = {
            enabled            = true,
            size               = 2,
            passes             = 2,
            popups             = true,
            -- Keep at 0.30: lower values blur the popup's own drop SHADOW (low-alpha
            -- pixels), an ugly halo (also seen on Chrome/GTK menus). Popovers instead
            -- floor their background alpha (popoverAlpha ≥ 0.38) so the content still blurs.
            popups_ignorealpha = 0.30,
            ignore_opacity     = true,
            new_optimizations  = true,
            xray               = false,
            noise              = 0.01,
            contrast           = 1.2,
            brightness         = 0.8,
            vibrancy           = 0.4,
            vibrancy_darkness  = 0.1,
        },

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 2,
            color        = "rgba(00000055)",
        },
    },

    input = {
        kb_layout               = "us",
        follow_mouse            = 1,
        float_switch_override_focus = 0,
        touchpad = {
            natural_scroll = false,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo        = true,
        disable_splash_rendering     = true,
        force_default_wallpaper      = 0,
        -- Fallback color shown for the brief window where awww-daemon is already
        -- torn down (background-graphical.slice stops early on logout/reboot) but
        -- Hyprland hasn't exited yet. Dark neutral instead of Hyprland's gray+splash.
        background_color             = 0x101014,
        allow_session_lock_restore   = true,
        -- Compositor-level wake fallback: hypridle's on-resume only fires if its
        -- own idle tracking saw the timeout (a daemon restart or inhibitor churn
        -- resets it, leaving the screen black with no way back — incident 2026-06-10).
        -- With these, any input re-enables DPMS regardless of hypridle's state.
        mouse_move_enables_dpms      = true,
        key_press_enables_dpms       = true,
    },

    ecosystem = {
        no_update_news = true,
    },
})


-- ── Animations ────────────────────────────────────────────────────────────────
hl.curve("myBezier",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("easeOut",   { type = "bezier", points = { {0.0,  0.0}, {0.2,  1.0} } })

hl.animation({ leaf = "windows",    enabled = true,  speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true,  speed = 4,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true,  speed = 10, bezier = "default" })
hl.animation({ leaf = "fade",          enabled = true, speed = 4,   bezier = "easeOut" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3,   bezier = "easeOut" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3,   bezier = "easeOut", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 2,   bezier = "easeOut", style = "fade" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 6,   bezier = "default" })


-- ── Crystal Shell startup ─────────────────────────────────────────────────────
hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm finalize")
    -- The shell runs as a systemd user unit so it respawns on crash (segfault etc.)
    -- instead of leaving a bare compositor. We START it explicitly here (the unit is
    -- intentionally NOT enabled via graphical-session.target — that would leak the UI
    -- into every Hyprland session; see bin/crystal-shell.service). `finalize`
    -- above has just activated graphical-session.target, which the unit orders After.
    hl.exec_cmd("systemctl --user start crystal-shell.service")
    -- Background daemons go in background-graphical.slice (-s b), not the foreground
    -- app slice: systemd deprioritizes them under CPU/IO/memory pressure and the OOM
    -- killer targets them before real apps — correct for wallpaper/idle/clipboard helpers.
    hl.exec_cmd("uwsm app -s b -- awww-daemon")
    hl.exec_cmd("uwsm app -s b -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("uwsm app -s b -- hypridle")
    hl.exec_cmd("uwsm app -s b -- wl-paste --watch cliphist store")
end)


-- ── Programs ──────────────────────────────────────────────────────────────────
local terminal    = "kitty"
local fileManager = "nautilus"
local mainMod     = "SUPER"


-- ── Keybinds — Crystal Shell UI ──────────────────────────────────────────────
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("systemctl --user restart crystal-shell.service"))
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("crystal-lock"))

-- ── Keybinds — App launchers ─────────────────────────────────────────────────
hl.bind(mainMod .. " + S",   hl.dsp.exec_cmd("ags request toggleSettings"))
hl.bind("SUPER + SUPER_L",   hl.dsp.exec_cmd("ags request toggleAppGrid"), { release = true })
hl.bind(mainMod .. " + G",          hl.dsp.exec_cmd("ags request toggleGameOverlay"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("crystal-game-mode toggle"))
hl.bind(mainMod .. " + E",   hl.dsp.exec_cmd("uwsm app -- " .. fileManager))
hl.bind(mainMod .. " + T",   hl.dsp.exec_cmd("uwsm app -- " .. terminal))
hl.bind(mainMod .. " + Q",   hl.dsp.window.close())
hl.bind(mainMod .. " + M",   hl.dsp.exit())

-- ── Keybinds — Focus ─────────────────────────────────────────────────────────
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- ── Keybinds — Mouse drag & resize ───────────────────────────────────────────
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── Keybinds — Keyboard resize ───────────────────────────────────────────────
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x =  30, y =   0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.resize({ x = -30, y =   0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.resize({ x =   0, y = -30, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.resize({ x =   0, y =  30, relative = true }), { repeating = true })

-- ── Keybinds — Workspaces ────────────────────────────────────────────────────
for i = 1, 5 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- ── Keybinds — Window modes ──────────────────────────────────────────────────
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))

-- ── Keybinds — Screenshots ───────────────────────────────────────────────────
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy'))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(
    [[grim -g "$(slurp -d)" ~/Pictures/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png ]]
    .. [[&& notify-send "Captura" "Guardada en Imágenes"]]
))


-- ── Window rules ─────────────────────────────────────────────────────────────
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name  = "steam-popups",
    match = { class = "^steam$", title = "^$" },
    rounding = 0,
    no_anim  = true,
})

hl.window_rule({
    name  = "general-popups",
    match = { class = "^$" },
    no_anim  = true,
    rounding = 0,
})

-- The Crystal Shell "About" window (a small fixed-size GTK toplevel) floats and
-- centers. Matched by title since AGS windows share the io.Astal.ags class.
hl.window_rule({
    name   = "float-about",
    match  = { title = "^About Crystal Shell$" },
    float  = true,
    center = true,
})


-- ── Game mode — workspace, window rules & auto-return ────────────────────────
local lastNonGameWs    = nil
local prevWallpaper    = nil
local prevTransition   = "fade"
local gameMonitor      = ""
local activeGames      = {}   -- address → appid; tracks all Steam-launched game windows

local function getSteamAppId(pid)
    local p = tonumber(pid)
    for _ = 1, 8 do
        if not p or p <= 1 then break end
        local ef = io.open("/proc/" .. p .. "/environ", "rb")
        if ef then
            local env = ef:read("*a"); ef:close()
            local appid = env:match("SteamAppId=(%d+)")
                       or env:match("SteamGameId=(%d+)")
                       or env:match("STEAM_APP_ID=(%d+)")
            if appid and appid ~= "0" then return appid end
        end
        local sf = io.open("/proc/" .. p .. "/stat", "r")
        if not sf then break end
        local stat = sf:read("*l"); sf:close()
        p = tonumber(stat:match("%)%s+%S+%s+(%d+)"))
    end
    return nil
end

local function readGamingCfg()
    local f = io.open(os.getenv("HOME") .. "/.config/crystal-shell/gaming.json", "r")
    if not f then return nil, nil, "grow", false end
    local raw = f:read("*a"); f:close()
    local mode       = raw:match('"wallpaperMode"%s*:%s*"([^"]+)"')
    local custom     = raw:match('"customWallpaper"%s*:%s*"([^"]+)"')
    local transition = raw:match('"transition"%s*:%s*"([^"]+)"') or "grow"
    local perfOn     = raw:match('"performanceProfile"%s*:%s*(true)') ~= nil
    return mode, custom, transition, perfOn
end

local function readWallpaperCfg()
    local f = io.open(os.getenv("HOME") .. "/.config/crystal-shell/wallpaper", "r")
    if not f then return nil, "fade" end
    local raw = f:read("*a"); f:close()
    return raw:match('"path"%s*:%s*"([^"]+)"'),
           raw:match('"transition"%s*:%s*"([^"]+)"') or "fade"
end

local function findSteamHero(appid)
    local base = os.getenv("HOME") .. "/.steam/steam/appcache/librarycache/" .. appid
    local flat = base .. "/library_hero.jpg"
    local f = io.open(flat, "r")
    if f then f:close(); return flat end
    local iter = io.popen('find "' .. base .. '" -maxdepth 2 -name "library_hero.jpg" 2>/dev/null | grep -v blur | head -1')
    if iter then
        local path = iter:read("*l"); iter:close()
        if path then path = path:match("^%s*(.-)%s*$") end
        if path and path ~= "" then return path end
    end
    return nil
end

hl.on("workspace.active", function(ws)
    if ws.name ~= "gamespace" then
        lastNonGameWs = ws.id
    end
end)

hl.on("window.open", function(w)
    local cls = w.class or ""
    local pid = w.pid or 0
    local appid = cls:match("^steam_app_(%d+)$") or getSteamAppId(pid)
    if not appid then return end

    activeGames[w.address] = appid
    hl.dispatch(hl.dsp.window.move({ workspace = "name:gamespace" }))
    hl.dispatch(hl.dsp.focus({ workspace = "name:gamespace" }))
    hl.exec_cmd("hyprctl setprop address:" .. w.address .. " immediate 1 lock:0")

    if prevWallpaper then return end

    local ws = hl.get_active_workspace()
    local mon = ws and ws.monitor
    gameMonitor = (type(mon) == "string" and mon ~= "") and mon or ""

    local mode, custom, transition, perfOn = readGamingCfg()
    if perfOn then hl.exec_cmd("powerprofilesctl set performance") end

    local wallpaperPath = nil
    if mode == "artwork" then
        wallpaperPath = findSteamHero(appid)
    elseif mode == "custom" and custom and custom ~= "" then
        wallpaperPath = custom
    end

    if wallpaperPath then
        prevWallpaper, prevTransition = readWallpaperCfg()
        local outputFlag = (gameMonitor ~= "") and (" --outputs " .. gameMonitor) or ""
        -- No transition on entry: game covers the wallpaper immediately anyway,
        -- animating it causes awww to freeze mid-transition until the game closes.
        os.execute("awww img " .. wallpaperPath .. " --transition-type none" .. outputFlag)
    end
end)

hl.on("window.destroy", function(w)
    if not activeGames[w.address] then return end
    activeGames[w.address] = nil

    hl.timer(function()
        local hasMore = false
        for _ in pairs(activeGames) do hasMore = true; break end

        local activeWs = hl.get_active_workspace()
        if not hasMore and lastNonGameWs ~= nil and activeWs and activeWs.name == "gamespace" then
            hl.dispatch(hl.dsp.focus({ workspace = lastNonGameWs }))
            local _, _, _, perfOn = readGamingCfg()
            if perfOn then hl.exec_cmd("powerprofilesctl set balanced") end
            if prevWallpaper then
                local outputFlag = (gameMonitor ~= "") and (" --outputs " .. gameMonitor) or ""
                os.execute("awww img " .. prevWallpaper .. " --transition-type " .. prevTransition .. outputFlag)
                prevWallpaper = nil
            end
        end
    end, { timeout = 3000, type = "oneshot" })
end)


hl.workspace_rule({
    workspace    = "name:gamespace",
    gaps_in      = 0,
    gaps_out     = 0,
    no_border    = true,
    border_size  = 0,
    no_rounding  = true,
    no_shadow    = true,
    decorate     = false,
    persistent   = false,
    animation    = "fade",
})

-- All windows on gamespace get full performance treatment regardless of class
hl.window_rule({
    name         = "gamespace-perf",
    match        = { workspace = "name:gamespace" },
    no_blur      = true,
    no_anim      = true,
    no_dim       = true,
    no_shadow    = true,
    rounding     = 0,
    border_size  = 0,
    opaque       = true,
    force_rgbx   = true,
    immediate    = true,
    idle_inhibit = "focus",
    decorate     = false,
})

-- Fallback workspace assignment for steam_app_* (belt+suspenders with the Lua handler)
hl.window_rule({
    name      = "steam-games-to-gamespace",
    match     = { class = "^steam_app_" },
    workspace = "name:gamespace",
})

-- Also catch games that self-report content type (XDG game = 3)
hl.window_rule({
    name      = "content-game-to-gamespace",
    match     = { content = 3 },
    workspace = "name:gamespace",
})


-- ── Layer rules ───────────────────────────────────────────────────────────────
hl.layer_rule({ match = { namespace = "crystal-bar" },      blur = true, ignore_alpha = 0.05  })
hl.layer_rule({ match = { namespace = "crystal-dock" },     blur = true, ignore_alpha = 0.04 })
hl.layer_rule({ match = { namespace = "notif-win" },        blur = true, ignore_alpha = 0.001 })
hl.layer_rule({ match = { namespace = "crystal-lock" },     blur = true, ignore_alpha = 0.3   })


-- ── Lock screen submap ────────────────────────────────────────────────────────
-- crystal-lock activates with:  hyprctl dispatch 'hl.dsp.submap("lock")'
-- crystal-lock resets with:     hyprctl dispatch 'hl.dsp.submap("reset")'
hl.define_submap("lock", function()
    hl.bind("SUPER + SHIFT + CTRL + ALT + Escape", hl.dsp.submap("reset"))
end)


-- ── Crystal Shell generated settings ─────────────────────────────────────────
-- Auto-generated by the Crystal Shell Settings UI. Do not edit manually.
safe_require("crystal-settings")
safe_require("crystal-monitor")

-- ── User overrides ────────────────────────────────────────────────────────────
-- Your personal config: keyboard layout, monitors, startup apps, keybinds, etc.
-- This file is never overwritten by updates.
safe_require("hyprland-user")
