-- ─────────────────────────────────────────────────────────────────────────────
-- Nidara — Hyprland Lua configuration  (requires Hyprland ≥ 0.55)
-- Installed to /usr/share/nidara/config/hypr/hyprland.lua
-- Do NOT edit this file directly. Use ~/.config/nidara/hyprland-user.lua
-- for personal overrides (keyboard layout, monitors, startup apps, etc.)
-- ─────────────────────────────────────────────────────────────────────────────

-- Extend the Lua path so require() can find generated files in nidara's
-- config directory (nidara-settings.lua, nidara-monitor.lua, hyprland-user.lua)
local home = os.getenv("HOME")
package.path = package.path
    .. ";" .. home .. "/.config/nidara/?.lua"
    .. ";" .. home .. "/.config/hypr/?.lua"

-- Soft-load a module: missing files produce a notification, not a crash.
-- The handler itself is pcall-guarded: it once called a non-existent
-- hl.notify(), so the "soft" path crashed the WHOLE config load on any
-- machine missing a user .lua (caught by the CI smoke test's screenshot).
local function safe_require(mod)
    local ok, err = pcall(require, mod)
    if not ok then
        local msg = "Nidara: failed to load " .. mod .. ".lua\n" .. tostring(err)
        local notified = pcall(function()
            hl.notification.create({ text = msg, duration = 8000 })
        end)
        if not notified then print(msg) end
    end
end


-- ── Wallpaper state ───────────────────────────────────────────────────────────
-- The single source of truth for the wallpaper is ~/.config/nidara/wallpaper
-- (JSON, written by the shell's WallpaperManager, shown in Settings, resolved by
-- the greeter and lockscreen through ui/lib/wallpaper.ts). awww keeps a cache of
-- its own, but that cache is NOT authoritative — see the startup block below.
local DEFAULT_WALLPAPER = "/usr/share/nidara/wallpaper.jpg"

local function readWallpaperCfg()
    local f = io.open(home .. "/.config/nidara/wallpaper", "r")
    if not f then return nil, "fade" end
    local raw = f:read("*a"); f:close()
    return raw:match('"path"%s*:%s*"([^"]+)"'),
           raw:match('"transition"%s*:%s*"([^"]+)"') or "fade"
end

-- Path the desktop should paint: the saved wallpaper if it still exists on disk
-- (a deleted image or an unmounted drive falls through), else the shipped
-- default. Mirrors resolveWallpaper() in ui/lib/wallpaper.ts.
local function resolveWallpaper()
    local saved = readWallpaperCfg()
    if saved and saved ~= "" then
        local f = io.open(saved, "r")
        if f then f:close(); return saved end
    end
    return DEFAULT_WALLPAPER
end

-- Single-quote a string for the shell (POSIX: close, escape, reopen), so paths
-- with spaces or quotes survive the trip through exec.
local function shquote(s)
    local escaped = tostring(s):gsub("'", "'\\''")
    return "'" .. escaped .. "'"
end


-- ── Monitor ───────────────────────────────────────────────────────────────────
-- Per-monitor overrides live in nidara-monitor.lua (sourced at the bottom).
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })


-- ── Look & feel ───────────────────────────────────────────────────────────────
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 8,
        border_size = 1,
        col = {
            active_border   = { colors = {"rgba(ffffff4d)", "rgba(ffffff1a)"}, angle = 45 },
            inactive_border = "rgba(59595933)",
        },
        layout           = "dwindle",
        resize_on_border = true,
        allow_tearing    = true,
    },

    decoration = {
        rounding       = 24,
        rounding_power = 3.2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        blur = {
            enabled            = true,
            size               = 2,
            passes             = 2,
            popups             = true,
            -- Keep at 0.30: lower values blur the popup's own drop SHADOW (low-alpha
            -- pixels), an ugly halo (also seen on Chrome/GTK menus). Popovers instead
            -- floor their background alpha (popoverAlpha ≥ 0.38) so the content still blurs.
            popups_ignorealpha = 0.30,
            ignore_opacity     = true,
            new_optimizations  = true,
            xray               = false,
            noise              = 0.01,
            contrast           = 1.2,
            brightness         = 0.8,
            vibrancy           = 0.4,
            vibrancy_darkness  = 0.1,
        },

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 2,
            color        = "rgba(00000055)",
        },

        -- Inner glow (Hyprland ≥ 0.56) — OFF here and owned by the SHELL, which
        -- turns it on only while the built-in Assistant is running a turn:
        -- "the AI is working in this window". core/AgentGlow.ts is the only
        -- thing that ever flips `enabled`; everything else is set once, here.
        --
        -- `color_inactive` transparent is what makes this usable at all. The
        -- glow has no window rule (verified against the 0.56 binary: only these
        -- five options exist, all global), and `color_inactive` DEFAULTS TO
        -- `color` — leave it out and every window glows. Transparent means only
        -- the FOCUSED window does, which is exactly the invariant the agent's
        -- toolset already enforces: every action it takes acts on the focused
        -- window and refuses otherwise, so focused ≡ the window it is working in.
        glow = {
            enabled        = false,
            range          = 24,
            render_power   = 3,
            color          = { colors = {"rgba(9b6cffcc)", "rgba(4fc3ffcc)"}, angle = 45 },
            color_inactive = "rgba(00000000)",
        },
    },

    -- Groups (tabbed windows): same glass language as window borders. The
    -- groupbar tab colors below are a neutral fallback — the shell re-pushes
    -- the accent over groupbar col.active at boot and on accent change
    -- (ThemeManager.syncHyprlandGroupAccent). NOTE: a groupbar BAKES its
    -- colors when the group is created — config changes only affect groups
    -- made afterwards (verified live 2026-06-11).
    group = {
        col = {
            border_active          = { colors = {"rgba(ffffff4d)", "rgba(ffffff1a)"}, angle = 45 },
            border_inactive        = "rgba(59595933)",
            border_locked_active   = { colors = {"rgba(ffffff4d)", "rgba(ffffff1a)"}, angle = 45 },
            border_locked_inactive = "rgba(59595933)",
        },
        groupbar = {
            -- "Floating capsules": full-pill tabs deliberately DETACHED from
            -- the window (gaps_out) so the window's rounded top stays whole —
            -- a flush bar against a radius-24 window leaves a corner notch
            -- that can't be fixed (no per-corner rounding; per-window
            -- set_prop rounding was considered and REJECTED by the owner).
            enabled          = true,
            gradients        = true,
            render_titles    = true,
            height           = 28,
            font_size        = 12,
            indicator_height = 0,
            indicator_gap    = 0,
            gradient_rounding       = 14,
            gradient_rounding_power = 2.0,   -- full pill, like the bar capsules
            gaps_in          = 6,
            gaps_out         = 8,
            keep_upper_gap   = true,
            rounding         = 1,
            text_padding     = 14,
            text_color          = "rgba(ffffffee)",
            text_color_inactive = "rgba(ffffff99)",
            blur = false,
            col = {
                active          = "rgba(ffffff33)",
                inactive        = "rgba(ffffff14)",
                locked_active   = "rgba(ffffff33)",
                locked_inactive = "rgba(ffffff14)",
            },
        },
    },

    input = {
        kb_layout               = "us",
        -- 2 = pointer focus is DETACHED from keyboard focus: hovering still sends the
        -- window its motion/hover states, but only a CLICK moves the keyboard focus.
        -- Not a taste setting — it is what makes the bar's chrome reachable in a tiled
        -- session. Under `1`, travelling to the AppTitle capsule (or the dock, or the
        -- tray) crosses whatever windows lie on the way and re-focuses each of them, so
        -- the capsule renames itself mid-journey and you open the window menu for a
        -- window you never meant to act on. `0` would fix that too but also kills hover
        -- feedback inside apps. The window menu additionally CLOSES itself if focus
        -- moves while it is open (surfaces/bar/WindowMenu.ts) — that covers the paths a
        -- pointer setting cannot, like Alt+Tab.
        follow_mouse            = 2,
        float_switch_override_focus = 0,
        touchpad = {
            natural_scroll = false,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo        = true,
        disable_splash_rendering     = true,
        force_default_wallpaper      = 0,
        -- Fallback color shown for the brief window where awww-daemon is already
        -- torn down (background-graphical.slice stops early on logout/reboot) but
        -- Hyprland hasn't exited yet. Dark neutral instead of Hyprland's gray+splash.
        background_color             = 0x101014,
        allow_session_lock_restore   = true,
        -- Compositor-level wake fallback: hypridle's on-resume only fires if its
        -- own idle tracking saw the timeout (a daemon restart or inhibitor churn
        -- resets it, leaving the screen black with no way back — incident 2026-06-10).
        -- With these, any input re-enables DPMS regardless of hypridle's state.
        mouse_move_enables_dpms      = true,
        key_press_enables_dpms       = true,
    },

    ecosystem = {
        no_update_news = true,
    },
})


-- ── Animations ────────────────────────────────────────────────────────────────
hl.curve("myBezier",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("easeOut",   { type = "bezier", points = { {0.0,  0.0}, {0.2,  1.0} } })

hl.animation({ leaf = "windows",    enabled = true,  speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true,  speed = 4,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true,  speed = 10, bezier = "default" })
hl.animation({ leaf = "fade",          enabled = true, speed = 4,   bezier = "easeOut" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3,   bezier = "easeOut" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3,   bezier = "easeOut", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 2,   bezier = "easeOut", style = "fade" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 6,   bezier = "default" })

-- The Assistant's "taking this window over" sweep: on every focus change
-- Hyprland runs the glow gradient once around the border (onFocusAnimUpdate),
-- then stops. `speed` is TENTHS OF A SECOND PER LAP and inverted — bigger is
-- slower — so 30 = one 3 s lap.
--
-- Enabled here PERMANENTLY on purpose, even though the glow itself is off
-- almost always. Two measured facts (2026-08-01, 2560x1440@144, Hyprland CPU
-- jiffies + amdgpu gpu_busy_percent, focus flips as the load):
--   · Arming it live does NOT work. Enable it under an already-open window and
--     that window never sweeps again (2.5%/1.8% GPU/CPU = idle), while a window
--     created afterwards sweeps normally (3.4%/2.8%). The animated variable is
--     built with the window, so the config has to be in place BEFORE the window
--     exists — i.e. here, not from the shell at turn start.
--   · Leaving it armed while the glow is off is FREE (1.6%/1.6% ≈ idle): with
--     nothing painted there is nothing to damage.
-- NEVER add `style = "loop"`. A loop dirties the window every tick whatever it
-- paints — measured 32% GPU permanently, the SAME with the glow disabled or at
-- alpha 0, because re-compositing means re-blurring the bar and dock on top.
hl.animation({ leaf = "glowangle",     enabled = true, speed = 30,  bezier = "linear" })


-- ── Nidara startup ─────────────────────────────────────────────────────
hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm finalize")
    -- The shell runs as a systemd user unit so it respawns on crash (segfault etc.)
    -- instead of leaving a bare compositor. We START it explicitly here (the unit is
    -- intentionally NOT enabled via graphical-session.target — that would leak the UI
    -- into every Hyprland session; see bin/nidara.service). `finalize`
    -- above has just activated graphical-session.target, which the unit orders After.
    hl.exec_cmd("systemctl --user start nidara.service")
    -- Background daemons go in background-graphical.slice (-s b), not the foreground
    -- app slice: systemd deprioritizes them under CPU/IO/memory pressure and the OOM
    -- killer targets them before real apps — correct for wallpaper/idle/clipboard helpers.
    hl.exec_cmd("uwsm app -s b -- awww-daemon")
    -- Wallpaper. awww-daemon restores its own cache on startup, but that cache is
    -- NOT authoritative: it records the last `awww img` and nothing else, and the
    -- restore is ASYNCHRONOUS — the daemon builds and spawns
    -- `awww img --outputs=<out> --transition-type=none <path>` once each output is
    -- configured, so it lands some time AFTER the socket starts answering `query`.
    -- The old check here ("apply the shipped default only if nothing is being
    -- displayed") raced exactly that gap; when it won, it wrote the DEFAULT into
    -- the cache, which every later boot then faithfully restored — so the user's
    -- wallpaper was lost for good while Settings still showed it (2026-07-26).
    -- Instead: wait until every output reports an image (i.e. the daemon's own
    -- restore has landed), bounded at ~3 s for a fresh install whose cache is empty
    -- — `background_color` above covers that window — then assert the wallpaper
    -- from ~/.config/nidara/wallpaper over it. One authoritative apply, no race.
    -- The `||` is the last rung of the resolution chain: an existing but undecodable
    -- image falls through to the shipped default rather than leaving the desktop bare.
    hl.exec_cmd([==[sh -c 'i=0; while [ $i -lt 30 ]; do q=$(awww query 2>/dev/null); t=$(printf "%s\n" "$q" | grep -c .); d=$(printf "%s\n" "$q" | grep -c "image:"); [ "$t" -gt 0 ] && [ "$t" = "$d" ] && break; i=$((i+1)); sleep 0.1; done; awww img "$1" --transition-type none || awww img "$2" --transition-type none' nidara-wallpaper ]==]
        .. shquote(resolveWallpaper()) .. " " .. shquote(DEFAULT_WALLPAPER))
    hl.exec_cmd("uwsm app -s b -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    -- GNOME keyring, secrets component only. PAM started the daemon at login holding
    -- the login password (nidara-setup wires pam_gnome_keyring into greetd) but left it
    -- deliberately uninitialized: THIS line is the `--start` it has been waiting for, and
    -- completing initialization is what unlocks the login keyring. It is not a formality —
    -- skip it and the session has secrets nobody can read. The other half of the deal is
    -- in nidara-setup: gnome-keyring-daemon.socket must be masked AND not running, or it
    -- wins the race for $XDG_RUNTIME_DIR/keyring/control and the PAM daemon exits with the
    -- password still in hand (masked-but-already-running is just as fatal as unmasked).
    -- Result: org.freedesktop.secrets for the built-in Assistant's API key plus git/VS
    -- Code/browser credentials. Secrets only (no ssh/gpg agent takeover).
    hl.exec_cmd("uwsm app -s b -- gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("uwsm app -s b -- hypridle")
    -- TWO watchers, one per generic type — not one untyped watcher. With no --type,
    -- wl-paste picks the mime type itself, and its order (src/wl-paste.c,
    -- mime_type_to_request) is: text/plain;charset=utf-8 → text/plain → ANY text/* →
    -- only then anything else. A browser's "Copy image" offers image/png alongside a
    -- text/html or text/plain flavour of the source URL, so `try_any_text` matched
    -- first and cliphist stored the URL — every single time. Symptom the user sees:
    -- "copy image" and "copy image address" produce the same clipboard entry, and no
    -- image ever reaches the history (measured: 0 binary entries in an 82 MB, 750-item
    -- db). The image path itself was never broken — an image-ONLY offer stored fine.
    -- `--type image` is the only way to make wl-paste ask for the bitmap when text is
    -- also on offer; `--type text` reproduces today's order exactly for text offers and
    -- simply skips offers with no text at all. A copy carrying both lands twice (one
    -- text row, one image row) — that is cliphist's documented setup, and it means
    -- either flavour is one click away.
    -- -max-items 50, not cliphist's default 750. 750 is tuned for its own CLI, which
    -- is fuzzel-searchable; our panel is a scroll list with no search, so anything past
    -- ~50 rows is storage nobody can reach (prior art: Win+V keeps 25, Klipper 20).
    -- It is also a size decision now that images are stored: measured on a real 750-item
    -- history, 549 rows were under 1 KB but EIGHTEEN were over 1 MB and ate 50 of the
    -- 60 MB — the tail is what costs, and it is unbounded per item (cliphist has no
    -- max-size flag). The flag rides the store command rather than a config file so
    -- there is one place to read and nothing to keep in sync. NOTE: cliphist trims to
    -- the limit on the NEXT store, all at once — lowering this deletes the surplus
    -- immediately, it does not age out.
    hl.exec_cmd("uwsm app -s b -- wl-paste --type text --watch cliphist -max-items 50 store")
    hl.exec_cmd("uwsm app -s b -- wl-paste --type image --watch cliphist -max-items 50 store")
end)


-- ── Programs ──────────────────────────────────────────────────────────────────
local terminal    = "kitty"
local fileManager = "nautilus"
local mainMod     = "SUPER"


-- ── Keybinds — Nidara UI ──────────────────────────────────────────────
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("systemctl --user restart nidara.service"))
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("nidara-lock"))

-- ── Keybinds — App launchers ─────────────────────────────────────────────────
hl.bind(mainMod .. " + S",   hl.dsp.exec_cmd("nidara-ipc openSettings"))
hl.bind("SUPER + SUPER_L",   hl.dsp.exec_cmd("nidara-ipc toggleAppGrid"), { release = true })
hl.bind(mainMod .. " + A",   hl.dsp.exec_cmd("nidara-ipc toggleAgent"))
hl.bind(mainMod .. " + B",          hl.dsp.exec_cmd("nidara-ipc toggleBarOverlay"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("nidara-game-mode toggle"))
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd("nidara-ipc disableComputerControl")) -- kill switch: revoke AI computer-control instantly
hl.bind(mainMod .. " + E",   hl.dsp.exec_cmd("uwsm app -- " .. fileManager))
hl.bind(mainMod .. " + T",   hl.dsp.exec_cmd("uwsm app -- " .. terminal))
hl.bind(mainMod .. " + Q",   hl.dsp.window.close())
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("nidara-ipc togglePrism"))
hl.bind(mainMod .. " + W",     hl.dsp.exec_cmd("nidara-ipc toggleOverview")) -- Workspace Overview (keyboard-navigable: ←/→ move, Enter switch, Esc close)
-- No exit-session bind on purpose (upstream ships SUPER+M = exit): one accidental
-- chord must never kill the whole session. Log out via the System Menu instead.
-- Our SUPER+M is maximize (Window modes below) — never rebind it to exit.

-- ── Keybinds — Focus ─────────────────────────────────────────────────────────
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
-- Alt+Tab cycles windows on the current workspace (the universal convention);
-- cycle_next({ next = false }) is the documented "previous" form (v0.55 Lua API).
hl.bind("ALT + TAB",         hl.dsp.window.cycle_next())
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }))

-- ── Keybinds — Mouse drag & resize ───────────────────────────────────────────
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── Keybinds — Keyboard resize ───────────────────────────────────────────────
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x =  30, y =   0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.resize({ x = -30, y =   0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.resize({ x =   0, y = -30, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.resize({ x =   0, y =  30, relative = true }), { repeating = true })

-- ── Keybinds — Workspaces ────────────────────────────────────────────────────
for i = 1, 5 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + SHIFT + right", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + SHIFT + left",  hl.dsp.window.move({ workspace = "e-1" }))

-- ── Keybinds — Window modes ──────────────────────────────────────────────────
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen())
-- Maximize = full working area WITHOUT covering the bar (fullscreen mode 1).
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized" }))

-- ── Keybinds — Screenshots ───────────────────────────────────────────────────
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy'))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(
    [[grim -g "$(slurp -d)" ~/Pictures/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png ]]
    .. [[&& notify-send "Captura" "Guardada en Imágenes"]]
))

-- ── Keybinds — Hardware / media keys ─────────────────────────────────────────
-- `locked` so they keep working on the lockscreen (GNOME/KDE behaviour).
-- wpctl ships with WirePlumber; brightnessctl and playerctl are install deps.
-- brightnessctl -n floors at 1 so the "down" key can never black the screen.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),        { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),       { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),     { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -n s 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -n s 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


-- ── Window rules ─────────────────────────────────────────────────────────────
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name  = "steam-popups",
    match = { class = "^steam$", title = "^$" },
    rounding = 0,
    no_anim  = true,
})

hl.window_rule({
    name  = "general-popups",
    match = { class = "^$" },
    no_anim  = true,
    rounding = 0,
})

-- The Nidara "About" window (a small fixed-size GTK toplevel) floats and
-- centers. Matched by title since AGS windows share the io.Astal.ags class.
hl.window_rule({
    name   = "float-about",
    match  = { title = "^About Nidara$" },
    float  = true,
    center = true,
})


-- ── Game mode — workspace, window rules & auto-return ────────────────────────
local lastNonGameWs    = nil
local inGameSession    = false
local prevWallpaper    = nil
local prevTransition   = "fade"
local prevProfile      = nil
local gameMonitor      = ""
local activeGames      = {}   -- address → appid; tracks all Steam-launched game windows

-- Reads the active power profile. Empty string when power-profiles-daemon is not
-- installed, which is the same as "nothing to put back".
local function currentProfile()
    local p = io.popen("powerprofilesctl get 2>/dev/null")
    if not p then return "" end
    local out = p:read("*l"); p:close()
    return out and out:match("^%s*(.-)%s*$") or ""
end

local function getSteamAppId(pid)
    local p = tonumber(pid)
    for _ = 1, 8 do
        if not p or p <= 1 then break end
        local ef = io.open("/proc/" .. p .. "/environ", "rb")
        if ef then
            local env = ef:read("*a"); ef:close()
            local appid = env:match("SteamAppId=(%d+)")
                       or env:match("SteamGameId=(%d+)")
                       or env:match("STEAM_APP_ID=(%d+)")
            if appid and appid ~= "0" then return appid end
        end
        local sf = io.open("/proc/" .. p .. "/stat", "r")
        if not sf then break end
        local stat = sf:read("*l"); sf:close()
        p = tonumber(stat:match("%)%s+%S+%s+(%d+)"))
    end
    return nil
end

local function readGamingCfg()
    local f = io.open(os.getenv("HOME") .. "/.config/nidara/gaming.json", "r")
    if not f then return nil, nil, "grow", false end
    local raw = f:read("*a"); f:close()
    local mode       = raw:match('"wallpaperMode"%s*:%s*"([^"]+)"')
    local custom     = raw:match('"customWallpaper"%s*:%s*"([^"]+)"')
    local transition = raw:match('"transition"%s*:%s*"([^"]+)"') or "grow"
    local perfOn     = raw:match('"performanceProfile"%s*:%s*(true)') ~= nil
    return mode, custom, transition, perfOn
end

local function findSteamHero(appid)
    local base = os.getenv("HOME") .. "/.steam/steam/appcache/librarycache/" .. appid
    local flat = base .. "/library_hero.jpg"
    local f = io.open(flat, "r")
    if f then f:close(); return flat end
    local iter = io.popen('find "' .. base .. '" -maxdepth 2 -name "library_hero.jpg" 2>/dev/null | grep -v blur | head -1')
    if iter then
        local path = iter:read("*l"); iter:close()
        if path then path = path:match("^%s*(.-)%s*$") end
        if path and path ~= "" then return path end
    end
    return nil
end

hl.on("workspace.active", function(ws)
    if ws.name ~= "gamespace" then
        lastNonGameWs = ws.id
    end
end)

hl.on("window.open", function(w)
    local cls = w.class or ""
    local pid = w.pid or 0
    local appid = cls:match("^steam_app_(%d+)$") or getSteamAppId(pid)
    if not appid then return end

    activeGames[w.address] = appid
    hl.dispatch(hl.dsp.window.move({ workspace = "name:gamespace" }))
    hl.dispatch(hl.dsp.focus({ workspace = "name:gamespace" }))
    hl.exec_cmd("hyprctl setprop address:" .. w.address .. " immediate 1 lock:0")

    -- "Already in a game session" — one flag, not `prevWallpaper`. That variable is
    -- only set when a wallpaper was actually swapped, so with mode = none (or
    -- artwork with no hero art found) a second game window re-ran this whole block.
    -- Harmless while the only thing it repeated was setting the profile to
    -- performance; not harmless now that entering CAPTURES the profile to put back,
    -- since the second pass would capture "performance" and restore that on exit.
    if inGameSession then return end
    inGameSession = true

    local ws = hl.get_active_workspace()
    local mon = ws and ws.monitor
    gameMonitor = (type(mon) == "string" and mon ~= "") and mon or ""

    local mode, custom, transition, perfOn = readGamingCfg()
    if perfOn then
        -- Remember what to go back to, exactly like the wallpaper below. Exit used
        -- to hard-code `balanced`, so a session started from Power saver ended in
        -- Balanced and the Settings choice was simply gone, silently.
        prevProfile = currentProfile()
        hl.exec_cmd("powerprofilesctl set performance")
    end

    local wallpaperPath = nil
    if mode == "artwork" then
        wallpaperPath = findSteamHero(appid)
    elseif mode == "custom" and custom and custom ~= "" then
        wallpaperPath = custom
    end

    if wallpaperPath then
        prevWallpaper, prevTransition = readWallpaperCfg()
        local outputFlag = (gameMonitor ~= "") and (" --outputs " .. gameMonitor) or ""
        -- No transition on entry: game covers the wallpaper immediately anyway,
        -- animating it causes awww to freeze mid-transition until the game closes.
        os.execute("awww img " .. wallpaperPath .. " --transition-type none" .. outputFlag)
    end
end)

hl.on("window.destroy", function(w)
    if not activeGames[w.address] then return end
    activeGames[w.address] = nil

    hl.timer(function()
        local hasMore = false
        for _ in pairs(activeGames) do hasMore = true; break end
        if hasMore then return end

        -- UNDOING THE SESSION and PUTTING THE USER BACK are two different jobs, and
        -- they used to share one condition. Everything below hung off "the user is
        -- standing on gamespace right now" — so quitting a game after wandering to
        -- another workspace left the game wallpaper up and the machine on
        -- performance, with the session flags still set, so the NEXT game got no
        -- entry either. Undoing is unconditional; only the focus return depends on
        -- where the user happens to be.
        inGameSession = false
        -- Put back what we found, not a guess. Only when the profile is STILL the
        -- one we set: if the user picked something else while the game ran, that is
        -- a newer decision than ours and restoring would undo it.
        if prevProfile and prevProfile ~= "" and currentProfile() == "performance" then
            hl.exec_cmd("powerprofilesctl set " .. prevProfile)
        end
        prevProfile = nil
        if prevWallpaper then
            local outputFlag = (gameMonitor ~= "") and (" --outputs " .. gameMonitor) or ""
            os.execute("awww img " .. prevWallpaper .. " --transition-type " .. prevTransition .. outputFlag)
            prevWallpaper = nil
        end

        local activeWs = hl.get_active_workspace()
        if lastNonGameWs ~= nil and activeWs and activeWs.name == "gamespace" then
            hl.dispatch(hl.dsp.focus({ workspace = lastNonGameWs }))
        end
    end, { timeout = 3000, type = "oneshot" })
end)


hl.workspace_rule({
    workspace    = "name:gamespace",
    gaps_in      = 0,
    gaps_out     = 0,
    no_border    = true,
    border_size  = 0,
    no_rounding  = true,
    no_shadow    = true,
    decorate     = false,
    persistent   = false,
    animation    = "fade",
})

-- All windows on gamespace get full performance treatment regardless of class
hl.window_rule({
    name         = "gamespace-perf",
    match        = { workspace = "name:gamespace" },
    no_blur      = true,
    no_anim      = true,
    no_dim       = true,
    no_shadow    = true,
    rounding     = 0,
    border_size  = 0,
    opaque       = true,
    force_rgbx   = true,
    immediate    = true,
    idle_inhibit = "focus",
    decorate     = false,
})

-- Fallback workspace assignment for steam_app_* (belt+suspenders with the Lua handler)
hl.window_rule({
    name      = "steam-games-to-gamespace",
    match     = { class = "^steam_app_" },
    workspace = "name:gamespace",
})

-- Also catch games that self-report content type (XDG game = 3)
hl.window_rule({
    name      = "content-game-to-gamespace",
    match     = { content = 3 },
    workspace = "name:gamespace",
})


-- ── Layer rules ───────────────────────────────────────────────────────────────
-- nidara-bar at 0.01 (was 0.05): during the overlays' close animation the glass
-- alpha drops below the threshold and the backdrop blur pops off; at 0.01 that
-- happens when the panel is already near-invisible. Verified no AA-edge halos
-- at rest.
-- blur_popups: the `blur` rule only blurs the layer SURFACE (and the Gtk.Overlay
-- children drawn on it — CC/NC/system menu/overview). Popups of the layer (a
-- Gtk.Popover: the glass tooltip, the dock context menu) are SEPARATE surfaces,
-- blurred by this rule — NOT by `decoration:blur:popups`, which only covers
-- popups of WINDOWS. Their content must clear `popups_ignorealpha` (0.30); the
-- tooltip floors its glass at 0.38 for exactly that. See tech-debt #26.
-- nidara-island: the Activity Island's expanded modes live in their OWN surface
-- on the OVERLAY level, one above the bar's TOP. That is the whole point: a
-- surface's blur samples what was composited BEFORE it, so this rule is what
-- finally difumina the bar's capsules under the island. Inside one window it
-- was impossible — Cairo has no backdrop-filter, so at the default 0.05 glass
-- the capsules read through sharp (see ui/shell/surfaces/island/IslandWindow.ts).
-- 0.01 like the bar, NOT the 0.30 a popup would need: `ignore_alpha` and
-- `popups_ignorealpha` are different knobs, which is why the island keeps its
-- 0.05 glass and stays tied to the user's opacity setting.
-- It needs `blur_popups` for the same reason the bar does, and shipped without
-- it: while the island lived inside the bar's window its popups were the BAR's
-- popups and this rule covered them. Moving it to its own surface moved them
-- too, and the player panel's source menu came out unblurred (user-caught
-- 2026-08-03). Any layer that can open a Gtk.Popover needs the flag.
-- nidara-app-grid: the app grid got its OWN surface on 2026-08-09 (it used to be a
-- child of the dock's window, which had to hand its whole blur region back for as
-- long as the grid was up — see AppGridWindow.ts). It keeps the DOCK's 0.04 rather
-- than the bar's 0.01 on purpose: 0.04 is what it has been blurred at all along,
-- and the reason the dock is not at 0.01 is app ICONS haloing, which is most of
-- what this surface paints. It opens context menus, hence blur_popups — the exact
-- flag the island shipped without when IT moved out of the bar.
hl.layer_rule({ match = { namespace = "nidara-bar" },      blur = true, blur_popups = true, ignore_alpha = 0.01  })
hl.layer_rule({ match = { namespace = "nidara-island" },   blur = true, blur_popups = true, ignore_alpha = 0.01  })
hl.layer_rule({ match = { namespace = "nidara-dock" },     blur = true, blur_popups = true, ignore_alpha = 0.04 })
hl.layer_rule({ match = { namespace = "nidara-app-grid" }, blur = true, blur_popups = true, ignore_alpha = 0.04 })
hl.layer_rule({ match = { namespace = "nidara-lock" },     blur = true, ignore_alpha = 0.3   })


-- ── Lock screen submap ────────────────────────────────────────────────────────
-- nidara-lock activates with:  hyprctl dispatch 'hl.dsp.submap("lock")'
-- nidara-lock resets with:     hyprctl dispatch 'hl.dsp.submap("reset")'
hl.define_submap("lock", function()
    hl.bind("SUPER + SHIFT + CTRL + ALT + Escape", hl.dsp.submap("reset"))
end)


-- ── Nidara generated settings ─────────────────────────────────────────
-- Auto-generated by the Nidara Settings UI. Do not edit manually.
safe_require("nidara-settings")
safe_require("nidara-monitor")

-- ── User overrides ────────────────────────────────────────────────────────────
-- Your personal config: keyboard layout, monitors, startup apps, keybinds, etc.
-- This file is never overwritten by updates.
safe_require("hyprland-user")
