-- ─────────────────────────────────────────────────────────────────────────────
-- Crystal Shell — Hyprland Lua configuration  (requires Hyprland ≥ 0.55)
-- Installed to /usr/share/crystal-shell/config/hypr/hyprland.lua
-- Do NOT edit this file directly. Use ~/.config/crystal-shell/hyprland-user.lua
-- for personal overrides (keyboard layout, monitors, startup apps, etc.)
-- ─────────────────────────────────────────────────────────────────────────────

-- Extend the Lua path so require() can find generated files in crystal-shell's
-- config directory (crystal-settings.lua, crystal-monitor.lua, hyprland-user.lua)
local home = os.getenv("HOME")
package.path = package.path
    .. ";" .. home .. "/.config/crystal-shell/?.lua"
    .. ";" .. home .. "/.config/hypr/?.lua"

-- Soft-load a module: missing files produce a notification, not a crash.
local function safe_require(mod)
    local ok, err = pcall(require, mod)
    if not ok then
        hl.notify("Crystal Shell: failed to load " .. mod .. ".lua\n" .. tostring(err), 8000)
    end
end


-- ── Monitor ───────────────────────────────────────────────────────────────────
-- Per-monitor overrides live in crystal-monitor.lua (sourced at the bottom).
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })


-- ── Look & feel ───────────────────────────────────────────────────────────────
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 8,
        border_size = 1,
        col = {
            active_border   = { colors = {"rgba(ffffff4d)", "rgba(ffffff1a)"}, angle = 45 },
            inactive_border = "rgba(59595933)",
        },
        layout           = "dwindle",
        resize_on_border = true,
    },

    decoration = {
        rounding       = 24,
        rounding_power = 3.2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        blur = {
            enabled            = true,
            size               = 1,
            passes             = 4,
            popups             = true,
            popups_ignorealpha = 0.30,
            ignore_opacity     = true,
            new_optimizations  = true,
            xray               = false,
            noise              = 0.01,
            contrast           = 1.2,
            brightness         = 0.8,
            vibrancy           = 0.4,
            vibrancy_darkness  = 0.1,
        },

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 2,
            color        = "rgba(00000055)",
        },
    },

    input = {
        kb_layout               = "us",
        follow_mouse            = 1,
        float_switch_override_focus = 0,
        touchpad = {
            natural_scroll = false,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo   = true,
        force_default_wallpaper = 0,
    },

    ecosystem = {
        no_update_news = true,
    },
})


-- ── Animations ────────────────────────────────────────────────────────────────
hl.curve("myBezier",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("easeOut",   { type = "bezier", points = { {0.0,  0.0}, {0.2,  1.0} } })

hl.animation({ leaf = "windows",    enabled = true,  speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true,  speed = 4,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true,  speed = 10, bezier = "default" })
hl.animation({ leaf = "fade",          enabled = true, speed = 4,   bezier = "easeOut" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3,   bezier = "easeOut" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3,   bezier = "easeOut", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 2,   bezier = "easeOut", style = "fade" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 6,   bezier = "default" })


-- ── Crystal Shell startup ─────────────────────────────────────────────────────
hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm finalize")
    hl.exec_cmd("uwsm app -- crystal-shell-ui")
    hl.exec_cmd("uwsm app -- awww-daemon")
    hl.exec_cmd("uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("uwsm app -- wl-paste --watch cliphist store")
end)


-- ── Programs ──────────────────────────────────────────────────────────────────
local terminal    = "kitty"
local fileManager = "nautilus"
local mainMod     = "SUPER"


-- ── Keybinds — Crystal Shell UI ──────────────────────────────────────────────
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("uwsm app -- crystal-shell-ui"))
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("crystal-lock"))

-- ── Keybinds — App launchers ─────────────────────────────────────────────────
hl.bind(mainMod .. " + S",   hl.dsp.exec_cmd("ags request toggleSettings"))
hl.bind("SUPER + SUPER_L",   hl.dsp.exec_cmd("ags request toggleAppGrid"), { release = true })
hl.bind(mainMod .. " + E",   hl.dsp.exec_cmd("uwsm app -- " .. fileManager))
hl.bind(mainMod .. " + T",   hl.dsp.exec_cmd("uwsm app -- " .. terminal))
hl.bind(mainMod .. " + Q",   hl.dsp.window.close())
hl.bind(mainMod .. " + M",   hl.dsp.exit())

-- ── Keybinds — Focus ─────────────────────────────────────────────────────────
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- ── Keybinds — Mouse drag & resize ───────────────────────────────────────────
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── Keybinds — Keyboard resize ───────────────────────────────────────────────
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x =  30, y =   0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.resize({ x = -30, y =   0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.resize({ x =   0, y = -30, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.resize({ x =   0, y =  30, relative = true }), { repeating = true })

-- ── Keybinds — Workspaces ────────────────────────────────────────────────────
for i = 1, 5 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- ── Keybinds — Window modes ──────────────────────────────────────────────────
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))

-- ── Keybinds — Screenshots ───────────────────────────────────────────────────
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy'))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(
    [[grim -g "$(slurp -d)" ~/Pictures/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png ]]
    .. [[&& notify-send "Captura" "Guardada en Imágenes"]]
))


-- ── Window rules ─────────────────────────────────────────────────────────────
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name  = "steam-popups",
    match = { class = "^steam$", title = "^$" },
    rounding = 0,
    no_anim  = true,
})

hl.window_rule({
    name  = "general-popups",
    match = { class = "^$" },
    no_anim  = true,
    rounding = 0,
})


-- ── Layer rules ───────────────────────────────────────────────────────────────
hl.layer_rule({ match = { namespace = "crystal-bar" },      blur = true, ignore_alpha = 0.05  })
hl.layer_rule({ match = { namespace = "crystal-dock" },     blur = true, ignore_alpha = 0.04 })
hl.layer_rule({ match = { namespace = "notif-win" },        blur = true, ignore_alpha = 0.001 })
hl.layer_rule({ match = { namespace = "crystal-launcher" }, blur = true, ignore_alpha = 0.001 })
hl.layer_rule({ match = { namespace = "crystal-lock" },     blur = true, ignore_alpha = 0.3   })


-- ── Lock screen submap ────────────────────────────────────────────────────────
-- crystal-lock activates with:  hyprctl dispatch submap lock
-- crystal-lock resets with:     hyprctl dispatch submap reset
hl.define_submap("lock", function()
    hl.bind("SUPER + SHIFT + CTRL + ALT + Escape", hl.dsp.submap("reset"))
end)


-- ── Plugin — Hyprglass Fluid Crystal Engine ───────────────────────────────────
if hl.plugin.hyprglass ~= nil then
    hl.config({
        plugin = {
            hyprglass = {
                enabled        = true,
                default_theme  = "dark",
                default_preset = "glass",
                preset         = "name:glass, blur_strength:0.5, refraction_strength:0.7, chromatic_aberration:0.4, lens_distortion:0.1, fresnel_strength:0.1, edge_thickness:0.05, vibrancy:0.7, vibrancy_darkness:0.1, adaptive_boost:0.5, adaptive_dim:0.3, glass_opacity:1",
                layers = {
                    enabled    = false,
                    namespaces = "crystal-dock, crystal-bar, notif-win, crystal-launcher",
                },
            },
        },
    })
end


-- ── Crystal Shell generated settings ─────────────────────────────────────────
-- Auto-generated by the Crystal Shell Settings UI. Do not edit manually.
safe_require("crystal-settings")
safe_require("crystal-monitor")

-- ── User overrides ────────────────────────────────────────────────────────────
-- Your personal config: keyboard layout, monitors, startup apps, keybinds, etc.
-- This file is never overwritten by updates.
safe_require("hyprland-user")
