// mirror-probe — the two pure halves of the mirror measurement, without a network.
//
//   ./scripts/bundle.sh --js scripts/dev/mirror-probe.ts /tmp/mirror-probe.js && gjs -m /tmp/mirror-probe.js
//
// `lib/mirrors.ts` decides what goes into a pacman mirrorlist. Two of its three
// functions are pure and are exactly where a mistake would be silent: the
// invocation reflector is given, and the parse of what reflector says back. The
// third (`measureMirrors`) spawns a process and reaches the network, so it is
// not reachable here and is verified on a medium instead.
//
// ⚠️ What makes the parse worth pinning is the FAILURE it prevents. Its output
// is prepended to `/etc/pacman.d/mirrorlist` on the machine being installed; a
// regex that also matched commented lines would silently turn a stock
// `pacman-mirrorlist` — every server present and every one commented out — into
// four hundred uncommented servers in alphabetical order, which reads exactly
// like a successful measurement and is the opposite of one.

import { reflectorArgs, parseServers } from "../../ui/installer/lib/mirrors"

const print = (s: string) => console.log(s)
let failures = 0
function fail(name: string, msg: string): void {
  failures++
  print(`   ✗ ${name}: ${msg}`)
}

print("\n── the invocation ──────────────────────────────────────────────────────\n")

{
  const args = reflectorArgs("ES")
  const joined = args.join(" ")
  const checks: [string, boolean][] = [
    ["it is reflector", args[0] === "reflector"],
    ["the country is passed as a flag, not folded into another argument", args.includes("--country") && args[args.indexOf("--country") + 1] === "ES"],
    ["it ranks by rate — a download, not a published score", joined.includes("--sort rate")],
    ["https only: this list outlives the install", joined.includes("--protocol https")],
    ["a hanging mirror costs seconds, not the budget", joined.includes("--connection-timeout") && joined.includes("--download-timeout")],
  ]
  for (const [name, ok] of checks) {
    if (ok) print(`   ok           ${name}`)
    else fail(name, `args were: ${joined}`)
  }
}

{
  const world = reflectorArgs(null)
  if (world.includes("--country")) {
    fail("no country means no --country flag", `args were: ${world.join(" ")}`)
  } else {
    print("   ok           no country means no --country flag")
  }
  // The worldwide run and the narrowed one must ask for the same NUMBER of
  // servers, or the fallback quietly returns a different-sized list than the
  // thing it is standing in for.
  const n = (a: string[]) => a[a.indexOf("--number") + 1]
  if (n(world) !== n(reflectorArgs("ES"))) {
    fail("both runs ask for the same number of servers", `${n(reflectorArgs("ES"))} vs ${n(world)}`)
  } else {
    print("   ok           both runs ask for the same number of servers")
  }
}

print("\n── the parse ───────────────────────────────────────────────────────────\n")

interface ParseCase { name: string; input: string; want: string[] }

const CASES: ParseCase[] = [
  {
    // Real output, reflector 2023-5, `--country ES --sort rate` on 2026-09-08.
    name: "a real reflector list keeps its order",
    input: [
      "################################################################################",
      "################# Arch Linux mirrorlist generated by Reflector #################",
      "################################################################################",
      "",
      "# With:       reflector --protocol https --country ES --sort rate",
      "# When:       2026-09-08 01:52:50 UTC",
      "# Retrieved:  2026-09-08 01:52:50 UTC",
      "# Last Check: 2026-09-08 01:45:09 UTC",
      "",
      "Server = https://es.mirrors.cicku.me/archlinux/$repo/os/$arch",
      "Server = https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch",
      "Server = https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch",
    ].join("\n"),
    want: [
      "https://es.mirrors.cicku.me/archlinux/$repo/os/$arch",
      "https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch",
      "https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch",
    ],
  },
  {
    // 🔴 The one that matters. This is how `pacman-mirrorlist` ships, and a
    // parse that accepted it would report a measurement that never happened.
    name: "a stock commented mirrorlist yields NOTHING",
    input: [
      "## Arch Linux repository mirrorlist",
      "## Generated on 2026-01-01",
      "#",
      "## Spain",
      "#Server = https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch",
      "#Server = https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch",
      "   #Server = https://es.mirrors.cicku.me/archlinux/$repo/os/$arch",
    ].join("\n"),
    want: [],
  },
  {
    // reflector's own header contains the word `Server` in a sentence, and the
    // header is the first thing in every list it prints.
    name: "prose containing the word Server is not a server",
    input: [
      "# The Server list below was sorted by rate",
      "## Server = not a real entry, this line is a comment",
      "Server = https://real.example/$repo/os/$arch",
    ].join("\n"),
    want: ["https://real.example/$repo/os/$arch"],
  },
  {
    name: "an empty answer is an empty list, not a crash",
    input: "",
    want: [],
  },
  {
    // `--country BO` exits 1 with this on stderr and nothing on stdout
    // (measured 2026-09-08). The caller reads the exit code; this only has to
    // not invent a server out of an error message.
    name: "an error message is not a server",
    input: "error: no mirrors found",
    want: [],
  },
  {
    name: "whitespace around the equals sign is reflector's, not ours to reject",
    input: "Server=https://tight.example/$repo/os/$arch\n  Server  =  https://loose.example/$repo/os/$arch  ",
    want: ["https://tight.example/$repo/os/$arch", "https://loose.example/$repo/os/$arch"],
  },
]

for (const c of CASES) {
  const got = parseServers(c.input)
  const same = got.length === c.want.length && got.every((u, i) => u === c.want[i])
  if (same) print(`   ${String(got.length).padStart(2)} server(s)  ${c.name}`)
  else fail(c.name, `expected ${JSON.stringify(c.want)}, got ${JSON.stringify(got)}`)
}

print(failures === 0 ? "\nALL INVARIANTS HOLD" : `\n${failures} FAILURE(S)`)
imports.system.exit(failures === 0 ? 0 : 1)
