// mirror-probe — the two pure halves of the mirror measurement, without a network.
//
//   ./scripts/bundle.sh --js scripts/dev/mirror-probe.ts /tmp/mirror-probe.js && gjs -m /tmp/mirror-probe.js
//
// `lib/mirrors.ts` decides what goes into a pacman mirrorlist. Two of its three
// functions are pure and are exactly where a mistake would be silent: the
// invocation reflector is given, and the parse of what reflector says back. The
// third (`measureMirrors`) spawns a process and reaches the network, so it is
// not reachable here and is verified on a medium instead.
//
// ⚠️ What makes the parse worth pinning is the FAILURE it prevents. Its output
// is prepended to `/etc/pacman.d/mirrorlist` on the machine being installed; a
// regex that also matched commented lines would silently turn a stock
// `pacman-mirrorlist` — every server present and every one commented out — into
// four hundred uncommented servers in alphabetical order, which reads exactly
// like a successful measurement and is the opposite of one.

import GLib from "gi://GLib"
import { cappedMirrorlist, reflectorArgs, parseServers, withoutCustomServers } from "../../ui/installer/lib/mirrors"
import { assemblePlan } from "../../ui/installer/lib/plan"
import type { Answers } from "../../ui/installer/lib/answers"
import type { BaseConfigResult } from "../../ui/installer/lib/base-config"

const print = (s: string) => console.log(s)
let failures = 0
function fail(name: string, msg: string): void {
  failures++
  print(`   ✗ ${name}: ${msg}`)
}

print("\n── the invocation ──────────────────────────────────────────────────────\n")

{
  const args = reflectorArgs("ES")
  const joined = args.join(" ")
  const checks: [string, boolean][] = [
    ["it is reflector", args[0] === "reflector"],
    ["the country is passed as a flag, not folded into another argument", args.includes("--country") && args[args.indexOf("--country") + 1] === "ES"],
    ["it ranks by rate — a download, not a published score", joined.includes("--sort rate")],
    ["https only: this list outlives the install", joined.includes("--protocol https")],
    ["a hanging mirror costs seconds, not the budget", joined.includes("--connection-timeout") && joined.includes("--download-timeout")],
  ]
  for (const [name, ok] of checks) {
    if (ok) print(`   ok           ${name}`)
    else fail(name, `args were: ${joined}`)
  }
}

{
  const world = reflectorArgs(null)
  if (world.includes("--country")) {
    fail("no country means no --country flag", `args were: ${world.join(" ")}`)
  } else {
    print("   ok           no country means no --country flag")
  }
  // The worldwide run and the narrowed one must ask for the same NUMBER of
  // servers, or the fallback quietly returns a different-sized list than the
  // thing it is standing in for.
  const n = (a: string[]) => a[a.indexOf("--number") + 1]
  if (n(world) !== n(reflectorArgs("ES"))) {
    fail("both runs ask for the same number of servers", `${n(reflectorArgs("ES"))} vs ${n(world)}`)
  } else {
    print("   ok           both runs ask for the same number of servers")
  }
}

print("\n── the parse ───────────────────────────────────────────────────────────\n")

interface ParseCase { name: string; input: string; want: string[] }

const CASES: ParseCase[] = [
  {
    // Real output, reflector 2023-5, `--country ES --sort rate` on 2026-09-08.
    name: "a real reflector list keeps its order",
    input: [
      "################################################################################",
      "################# Arch Linux mirrorlist generated by Reflector #################",
      "################################################################################",
      "",
      "# With:       reflector --protocol https --country ES --sort rate",
      "# When:       2026-09-08 01:52:50 UTC",
      "# Retrieved:  2026-09-08 01:52:50 UTC",
      "# Last Check: 2026-09-08 01:45:09 UTC",
      "",
      "Server = https://es.mirrors.cicku.me/archlinux/$repo/os/$arch",
      "Server = https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch",
      "Server = https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch",
    ].join("\n"),
    want: [
      "https://es.mirrors.cicku.me/archlinux/$repo/os/$arch",
      "https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch",
      "https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch",
    ],
  },
  {
    // 🔴 The one that matters. This is how `pacman-mirrorlist` ships, and a
    // parse that accepted it would report a measurement that never happened.
    name: "a stock commented mirrorlist yields NOTHING",
    input: [
      "## Arch Linux repository mirrorlist",
      "## Generated on 2026-01-01",
      "#",
      "## Spain",
      "#Server = https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch",
      "#Server = https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch",
      "   #Server = https://es.mirrors.cicku.me/archlinux/$repo/os/$arch",
    ].join("\n"),
    want: [],
  },
  {
    // reflector's own header contains the word `Server` in a sentence, and the
    // header is the first thing in every list it prints.
    name: "prose containing the word Server is not a server",
    input: [
      "# The Server list below was sorted by rate",
      "## Server = not a real entry, this line is a comment",
      "Server = https://real.example/$repo/os/$arch",
    ].join("\n"),
    want: ["https://real.example/$repo/os/$arch"],
  },
  {
    name: "an empty answer is an empty list, not a crash",
    input: "",
    want: [],
  },
  {
    // `--country BO` exits 1 with this on stderr and nothing on stdout
    // (measured 2026-09-08). The caller reads the exit code; this only has to
    // not invent a server out of an error message.
    name: "an error message is not a server",
    input: "error: no mirrors found",
    want: [],
  },
  {
    name: "whitespace around the equals sign is reflector's, not ours to reject",
    input: "Server=https://tight.example/$repo/os/$arch\n  Server  =  https://loose.example/$repo/os/$arch  ",
    want: ["https://tight.example/$repo/os/$arch", "https://loose.example/$repo/os/$arch"],
  },
]

for (const c of CASES) {
  const got = parseServers(c.input)
  const same = got.length === c.want.length && got.every((u, i) => u === c.want[i])
  if (same) print(`   ${String(got.length).padStart(2)} server(s)  ${c.name}`)
  else fail(c.name, `expected ${JSON.stringify(c.want)}, got ${JSON.stringify(got)}`)
}

print("\n── optional repositories (#492) ─────────────────────────────────────────\n")

{
  const mockBase: BaseConfigResult = {
    path: "mock.json",
    config: {
      custom_commands: ["SUDO_USER=nidara nidara-setup"],
      mirror_config: {
        optional_repositories: [],
      },
    },
  }

  const mockAnswers: Answers = {
    country: null,
    language: null,
    keyboard: null,
    timezone: null,
    disk: null,
    account: {
      fullName: "Test",
      username: "test",
      hostname: "test-box",
      password: "pass",
    },
  }

  const plan = assemblePlan(mockAnswers, mockBase)
  const opt = (plan.config.mirror_config as any)?.optional_repositories
  if (Array.isArray(opt) && opt.includes("multilib")) {
    print("   ok           assemblePlan injects multilib into optional_repositories")
  } else {
    fail("multilib in assemblePlan", `expected multilib in optional_repositories, got: ${JSON.stringify(opt)}`)
  }

  const planWithMirrors = assemblePlan(mockAnswers, mockBase, ["https://mirror.example.com"])
  const optWithMirrors = (planWithMirrors.config.mirror_config as any)?.optional_repositories
  if (Array.isArray(optWithMirrors) && optWithMirrors.includes("multilib")) {
    print("   ok           assemblePlan preserves multilib alongside measured mirrors")
  } else {
    fail("multilib with measured mirrors", `expected multilib preserved, got: ${JSON.stringify(optWithMirrors)}`)
  }
}

print("\n── earlier attempts' custom servers ─────────────────────────────────────\n")

{
  // The medium's own list, as it ships: a header, then servers.
  const STOCK = "##\n## Arch Linux repository mirrorlist\n##\n\n## Worldwide\nServer = https://geo.mirror.pkgbuild.com/$repo/os/$arch\n"
  // What archinstall writes, verbatim shape: `${block}\n\n${content}`.
  const block = (urls: string[]) => ["## Custom Servers", ...urls.map(u => `Server = ${u}`)].join("\n")
  const prepend = (content: string, urls: string[]) => `${block(urls)}\n\n${content}`
  const once = prepend(STOCK, ["https://a.example/$repo/os/$arch", "https://b.example/$repo/os/$arch"])
  // Three attempts, as measured on the VM.
  const thrice = prepend(prepend(once, ["https://c.example/$repo/os/$arch"]), ["https://d.example/$repo/os/$arch"])
  const cases: [string, string, string][] = [
    ["a stock list is left byte for byte", withoutCustomServers(STOCK), STOCK],
    ["one earlier attempt's block is removed", withoutCustomServers(once), STOCK],
    ["three stacked blocks are all removed", withoutCustomServers(thrice), STOCK],
    ["a Custom Servers header NOT at the top is the medium's own and stays",
      withoutCustomServers(STOCK + "\n## Custom Servers\nServer = https://x.example\n"),
      STOCK + "\n## Custom Servers\nServer = https://x.example\n"],
  ]
  for (const [name, got, want] of cases) {
    if (got === want) print(`   ok           ${name}`)
    else fail(name, `expected ${JSON.stringify(want)}, got ${JSON.stringify(got)}`)
  }
}

print("\n── the fallback the install waits on ────────────────────────────────────\n")

{
  // The medium's shape: country headers, alphabetical, everything uncommented.
  const many = (n: number) => Array.from({ length: n }, (_, i) =>
    `## Country ${i}\nServer = https://m${i}.example/$repo/os/$arch`).join("\n") + "\n"
  const MEDIUM = many(431)
  const capped = cappedMirrorlist(MEDIUM)
  const servers = (t: string) => t.split("\n").filter(l => /^Server\s*=/.test(l))

  const checks: [string, boolean, string][] = [
    ["431 servers become 20", servers(capped).length === 20, `${servers(capped).length}`],
    ["the first and the last survive, so the spread covers the file",
      servers(capped)[0] === "Server = https://m0.example/$repo/os/$arch"
      && servers(capped)[19] === "Server = https://m430.example/$repo/os/$arch",
      JSON.stringify([servers(capped)[0], servers(capped)[19]])],
    ["they are distinct — an even spread, not the same one twenty times",
      new Set(servers(capped)).size === 20, `${new Set(servers(capped)).size}`],
    ["they keep the file's order", servers(capped).join("\n") === [...servers(capped)].sort(
      (a, b) => Number(/m(\d+)\./.exec(a)![1]) - Number(/m(\d+)\./.exec(b)![1])).join("\n"), ""],
    ["the file says who shortened it and that the full list comes back",
      capped.includes("Nidara installer") && capped.includes("restored to the installed system"), ""],
    // Shorter lists are nobody's problem: a medium with twelve mirrors is left alone.
    ["a list already under the cap is untouched", cappedMirrorlist(many(12)) === many(12), ""],
    ["exactly the cap is untouched", cappedMirrorlist(many(20)) === many(20), ""],
  ]
  for (const [name, ok, got] of checks) {
    if (ok) print(`   ok           ${name}`)
    else fail(name, got)
  }
}

print(failures === 0 ? "\nALL INVARIANTS HOLD" : `\n${failures} FAILURE(S)`)
imports.system.exit(failures === 0 ? 0 : 1)
