#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# publish-ci-typings.sh — MAINTAINER ONLY. Snapshot the local @girs/ GI typings
# and publish them as a GitHub release asset so CI can type-check.
#
# Why this exists: `npm run typecheck` needs @girs/ (~58 MB of auto-generated
# .d.ts, git-ignored — committing it would bloat the repo). The typings are
# generated by `ags types`, which needs the ags binary + the Astal libraries
# installed — neither exists on a GitHub runner. But the OUTPUT is plain,
# platform-independent text that compresses to ~4 MB. So: a maintainer machine
# (which has everything) generates and uploads the snapshot once; CI downloads
# it on every run. No repo bloat, no Astal build in CI.
#
# When to re-run: whenever the GI typings change — i.e. after updating GTK,
# Astal, or any library whose API the shell code starts using. Symptom of a
# stale snapshot: the `typecheck` CI job fails on a type that exists locally.
#
# Usage:  ./scripts/dev/publish-ci-typings.sh        # package + upload
#         ./scripts/dev/publish-ci-typings.sh --dry  # package only, no upload
#
# Requires: gh (authenticated with repo write), zstd, a fresh @girs/
# (regenerate with: cd ui/ags-v3 && rm -rf @girs && ags types -d .)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
GIRS_DIR="$REPO_DIR/ui/ags-v3/@girs"
TAG="ci-assets"
ASSET="girs-snapshot.tar.zst"
OUT="/tmp/$ASSET"

[ -d "$GIRS_DIR" ] || {
  echo "ERROR: $GIRS_DIR not found. Generate it first:"
  echo "  cd ui/ags-v3 && ags types -d ."
  exit 1
}

echo "Packaging @girs ($(du -sh "$GIRS_DIR" | cut -f1)) ..."
tar -C "$REPO_DIR/ui/ags-v3" -cf - @girs | zstd -19 -T0 -q -f -o "$OUT"
echo "  → $OUT ($(du -h "$OUT" | cut -f1))"

if [ "${1:-}" = "--dry" ]; then
  echo "Dry run — not uploading."
  exit 0
fi

# The ci-assets release is a storage slot, not a software release: prerelease,
# pinned to no particular commit, asset overwritten in place on each publish.
if ! gh release view "$TAG" >/dev/null 2>&1; then
  echo "Creating release '$TAG' (first publish) ..."
  gh release create "$TAG" --prerelease \
    --title "CI assets (not a software release)" \
    --notes "Storage slot for CI-only build inputs. Currently: \`$ASSET\`, the @girs/ GI typings snapshot consumed by the typecheck job. Regenerate + re-upload with \`scripts/dev/publish-ci-typings.sh\` after a GTK/Astal update."
fi

echo "Uploading $ASSET ..."
gh release upload "$TAG" "$OUT" --clobber
echo "Done. CI typecheck will use the new snapshot on its next run."
