import GObject from "gi://GObject"
import GLib from "gi://GLib"
import { writeFile } from "../../lib/file"
import hs, { compositorOption, type CompositorOption } from "./HyprlandState"
import { luaConfigBlock, luaLiteral, type LuaValue } from "./hyprland-lua"

/**
 * The input options Hyprland owns and this shell configures.
 *
 * ⚠️ This table is the WHOLE declaration. It used to be three hand-maintained
 * lists of the same ten options — the re-sync naming each one to read it, the
 * generated `.lua` template naming each one to write it, and the setters naming
 * each one a third time as a bare string — with nothing checking that the three
 * agreed. Miss the template and a setting applies live and is gone at the next
 * login; miss the re-sync and the next change to ANY input setting rewrites the
 * whole file from stale state and clobbers it. Neither failure says anything.
 *
 * 🔑 The lists had already come apart, and `kb_variant` is where it showed:
 * `setKbLayout` had to smuggle it through a hook and eval a second time,
 * because the variant had a place in the reader and in the file template but no
 * option path of its own in the writer's vocabulary. Giving it a row is the
 * whole fix, and the double eval goes with it.
 *
 * Order is the order of the generated file — `touchpad` last, so its nested
 * table closes the block.
 */
const OPTIONS = {
    pointerSpeed:          { opt: compositorOption("input:sensitivity", "float"), init: 0.0,
                             // Two decimals so the file does not churn between `0` and `0.00`.
                             literal: (v: number) => v.toFixed(2) },
    accelProfile:          { opt: compositorOption("input:accel_profile", "str"), init: "adaptive" },
    mouseNaturalScroll:    { opt: compositorOption("input:natural_scroll", "bool"), init: false },
    numlockOnBoot:         { opt: compositorOption("input:numlock_by_default", "bool"), init: false },
    kbLayout:              { opt: compositorOption("input:kb_layout", "str"), init: "us" },
    kbVariant:             { opt: compositorOption("input:kb_variant", "str"), init: "" },
    kbRepeatDelay:         { opt: compositorOption("input:repeat_delay", "int"), init: 600 },
    kbRepeatRate:          { opt: compositorOption("input:repeat_rate", "int"), init: 25 },
    touchpadNaturalScroll: { opt: compositorOption("input:touchpad:natural_scroll", "bool"), init: false },
    touchpadTap:           { opt: compositorOption("input:touchpad:tap_to_click", "bool"), init: true },
}

type InputKey = keyof typeof OPTIONS
type InputState = { [K in InputKey]: (typeof OPTIONS)[K]["init"] }

/** The rows are heterogeneous by design — each carries its own value type — so
 *  the generic passes over the table erase it once, here, rather than at every
 *  use. Each row's `opt` and `literal` still agree with its own `init` type; it
 *  is only the LOOP that cannot say so. */
type AnyRow = { opt: CompositorOption<any>; init: LuaValue; literal?: (v: any) => string }
const rows = () => Object.entries(OPTIONS) as [InputKey, AnyRow][]

const CONFIG_PATH = GLib.build_filenamev([
    GLib.get_home_dir(), ".config", "nidara", "nidara-settings.lua",
])

const HEADER = [
    "-- NIDARA SHELL SETTINGS",
    "-- Auto-generated by the Nidara Settings UI. Do not edit manually.",
].join("\n")

class InputConfig extends GObject.Object {
    static {
        GObject.registerClass({
            GTypeName: "InputConfigManager",
            Signals: {
                changed: {},
            },
        }, this)
    }

    private state: InputState = Object.fromEntries(
        rows().map(([key, row]) => [key, row.init]),
    ) as InputState

    private _initPromise: Promise<void> | null = null

    constructor() {
        super()
        this._initPromise = this.syncFromHyprland()
        // Re-read the effective input options whenever Hyprland reloads its config
        // (e.g. the user edits hyprland-user.lua and runs `hyprctl reload`). Without
        // this, the next setX() would rewrite nidara-settings.lua from our stale
        // in-memory state and clobber the user's external change.
        hs.connect("config-reloaded", () => {
            this._initPromise = this.syncFromHyprland()
        })
    }

    get pointerSpeed() { return this.state.pointerSpeed }
    get accelProfile() { return this.state.accelProfile }
    get mouseNaturalScroll() { return this.state.mouseNaturalScroll }
    get touchpadNaturalScroll() { return this.state.touchpadNaturalScroll }
    get touchpadTap() { return this.state.touchpadTap }
    get numlockOnBoot() { return this.state.numlockOnBoot }
    get kbLayout() { return this.state.kbLayout }
    get kbVariant() { return this.state.kbVariant }
    get kbRepeatDelay() { return this.state.kbRepeatDelay }
    get kbRepeatRate() { return this.state.kbRepeatRate }

    /**
     * Re-read every option's EFFECTIVE value from the compositor.
     *
     * Every read passes the CURRENT value as its fallback, so an option that
     * cannot be read leaves this object as it found it. That matters more here
     * than in a one-off read: `applyAndSave` rewrites the whole of
     * nidara-settings.lua from this state, so anything this gets wrong is not
     * just displayed wrong, it is persisted and applied on the next change to
     * any input setting.
     *
     * ⚠️ The typed readers are not a style preference. Reading a bool option off
     * the raw JSON as `.int === 1` is `undefined === 1` — false for every
     * boolean, with nothing reporting it (#338). The option's `kind` in the
     * table above is what picks the right reader now, so the mistake has nowhere
     * left to be made.
     */
    private async syncFromHyprland(): Promise<void> {
        for (const [key, row] of rows()) {
            this.state[key] = await row.opt.read(this.state[key]) as never
        }
        this.emit("changed")
    }

    /**
     * The two halves of a compositor-backed write, in one place.
     *
     * A patch rather than a single option because some settings ARE two options:
     * a keyboard layout and its variant have to land together or the compositor
     * spends a moment with one applied and not the other. They share one file
     * write and one `changed`.
     */
    private async applyAndSave(patch: Partial<InputState>) {
        if (this._initPromise) {
            await this._initPromise
        }

        for (const [key, value] of Object.entries(patch) as [InputKey, LuaValue][]) {
            if (value === undefined) continue
            const row = OPTIONS[key] as AnyRow
            this.state[key] = value as never
            // 1. Live apply. The config uses Hyprland's Lua parser, which REJECTS
            // `hyprctl keyword` ("Use eval.") — so live changes go through eval.
            row.opt.apply(value)
        }

        // 2. Persist, so the change survives a restart the eval does not.
        this.persist()
        this.emit("changed")
    }

    private persist() {
        const entries = rows().map(([key, row]) => [
            row.opt.name,
            row.literal ? row.literal(this.state[key]) : luaLiteral(this.state[key]),
        ] as const)

        try {
            // `writeFile` rather than `GLib.file_set_contents`: both rename a
            // temporary into place, so neither can be caught half-written, but only
            // this one fsyncs. `hyprland.lua` requires this file at every login,
            // and a truncated require is the session with no Nidara config at all.
            writeFile(CONFIG_PATH, `${HEADER}\n${luaConfigBlock(entries)}\n`)
        } catch (e) {
            console.error("[InputConfig] Failed to write nidara-settings.lua:", e)
        }
    }

    setPointerSpeed(val: number) {
        return this.applyAndSave({ pointerSpeed: val })
    }

    setAccelProfile(val: string) {
        return this.applyAndSave({ accelProfile: val })
    }

    setMouseNaturalScroll(val: boolean) {
        return this.applyAndSave({ mouseNaturalScroll: val })
    }

    setTouchpadNaturalScroll(val: boolean) {
        return this.applyAndSave({ touchpadNaturalScroll: val })
    }

    setTouchpadTap(val: boolean) {
        return this.applyAndSave({ touchpadTap: val })
    }

    setNumlockOnBoot(val: boolean) {
        return this.applyAndSave({ numlockOnBoot: val })
    }

    setKbRepeatDelay(val: number) {
        return this.applyAndSave({ kbRepeatDelay: Math.round(val) })
    }

    setKbRepeatRate(val: number) {
        return this.applyAndSave({ kbRepeatRate: Math.round(val) })
    }

    /** Layout and variant are ONE change: a variant is meaningless against the
     *  wrong layout, so they apply and persist together. */
    setKbLayout(layout: string, variant = "") {
        return this.applyAndSave({ kbLayout: layout, kbVariant: variant })
    }
}

const inputConfig = new InputConfig()
export default inputConfig
