import GObject from "gi://GObject"
import GLib from "gi://GLib"
import hs from "./HyprlandState"

// Build a `hl.config({ input = { … } })` expression from a keyword-style option
// path ("input:touchpad:tap_to_click") + value, for `hyprctl eval`. String values
// are quoted; numbers/booleans pass through. The Lua parser rejects `hyprctl
// keyword`, so this is the only way to apply input options live.
function inputConfigEval(option: string, value: string | number): string {
    const path = option.replace(/^input:/, "").split(":")
    const lit = typeof value === "string" ? `"${value}"` : String(value)
    let inner = `${path[path.length - 1]} = ${lit}`
    for (let i = path.length - 2; i >= 0; i--) inner = `${path[i]} = { ${inner} }`
    return `hl.config({ input = { ${inner} } })`
}

class InputConfig extends GObject.Object {
    static {
        GObject.registerClass({
            GTypeName: "InputConfigManager",
            Signals: {
                changed: {},
            },
        }, this)
    }

    private _pointerSpeed = 0.0
    private _accelProfile = "adaptive"
    private _mouseNaturalScroll = false
    private _touchpadNaturalScroll = false
    private _touchpadTap = true
    private _numlockOnBoot = false
    private _kbLayout = "us"
    private _kbVariant = ""
    private _kbRepeatDelay = 600
    private _kbRepeatRate = 25

    private initialized = false

    constructor() {
        super()
        this.syncFromHyprland()
        // Re-read the effective input options whenever Hyprland reloads its config
        // (e.g. the user edits hyprland-user.lua and runs `hyprctl reload`). Without
        // this, the next setX() would rewrite crystal-settings.lua from our stale
        // in-memory state and clobber the user's external change.
        hs.connect("config-reloaded", () => this.syncFromHyprland())
    }

    get pointerSpeed() { return this._pointerSpeed }
    get accelProfile() { return this._accelProfile }
    get mouseNaturalScroll() { return this._mouseNaturalScroll }
    get touchpadNaturalScroll() { return this._touchpadNaturalScroll }
    get touchpadTap() { return this._touchpadTap }
    get numlockOnBoot() { return this._numlockOnBoot }
    get kbLayout() { return this._kbLayout }
    get kbVariant() { return this._kbVariant }
    get kbRepeatDelay() { return this._kbRepeatDelay }
    get kbRepeatRate() { return this._kbRepeatRate }

    // Parse options directly from Hyprland live state (via HyprlandState — the
    // single door to hyprctl)
    private async syncFromHyprland() {
        const opt = (name: string) => hs.getOptionJson(`input:${name}`)

        const sens = await opt("sensitivity")
        if (sens) this._pointerSpeed = sens.float || 0.0

        const accel = await opt("accel_profile")
        if (accel) {
            const raw = accel.str || ""
            this._accelProfile = (raw === "" || raw === "[[EMPTY]]") ? "adaptive" : raw
        }

        const mNat = await opt("natural_scroll")
        if (mNat) this._mouseNaturalScroll = mNat.int === 1

        const tNat = await opt("touchpad:natural_scroll")
        if (tNat) this._touchpadNaturalScroll = tNat.int === 1

        const tap = await opt("touchpad:tap_to_click")
        if (tap) this._touchpadTap = tap.int === 1

        const num = await opt("numlock_by_default")
        if (num) this._numlockOnBoot = num.int === 1

        const layout = await opt("kb_layout")
        if (layout) this._kbLayout = layout.str || "us"

        const variant = await opt("kb_variant")
        if (variant) this._kbVariant = variant.str || ""

        const delay = await opt("repeat_delay")
        if (delay) this._kbRepeatDelay = delay.int || 600

        const rate = await opt("repeat_rate")
        if (rate) this._kbRepeatRate = rate.int || 25

        this.initialized = true
        this.emit("changed")
    }

    private applyAndSave(option: string, value: string | number) {
        if (!this.initialized) return

        // 1. Live apply. The config uses Hyprland's Lua parser, which REJECTS
        // `hyprctl keyword` ("Use eval.") — so live changes go through eval.
        hs.evalLua(inputConfigEval(option, value))

        // 2. Save to persistent UI-owned file
        const configPath = GLib.build_filenamev([GLib.get_home_dir(), ".config", "crystal-shell", "crystal-settings.lua"])

        // Build the contents of the UI-managed override file
        const contents = `\
-- CRYSTAL SHELL SETTINGS
-- Auto-generated by the Crystal Shell Settings UI. Do not edit manually.
hl.config({
    input = {
        sensitivity        = ${this._pointerSpeed.toFixed(2)},
        accel_profile      = "${this._accelProfile}",
        natural_scroll     = ${this._mouseNaturalScroll},
        numlock_by_default = ${this._numlockOnBoot},
        kb_layout          = "${this._kbLayout}",
        kb_variant         = "${this._kbVariant}",
        repeat_delay       = ${this._kbRepeatDelay},
        repeat_rate        = ${this._kbRepeatRate},
        touchpad = {
            natural_scroll   = ${this._touchpadNaturalScroll},
            tap_to_click = ${this._touchpadTap},
        },
    },
})`

        try {
            const targetDir = GLib.path_get_dirname(configPath)
            if (!GLib.file_test(targetDir, GLib.FileTest.EXISTS)) {
                GLib.mkdir_with_parents(targetDir, 0o755)
            }
            GLib.file_set_contents(configPath, contents)
        } catch (e) {
            console.error("Failed to write crystal settings:", e)
        }

        this.emit("changed")
    }

    setPointerSpeed(val: number) {
        this._pointerSpeed = val
        this.applyAndSave("input:sensitivity", val)
    }

    setAccelProfile(val: string) {
        this._accelProfile = val
        this.applyAndSave("input:accel_profile", val)
    }

    setMouseNaturalScroll(val: boolean) {
        this._mouseNaturalScroll = val
        this.applyAndSave("input:natural_scroll", val ? 1 : 0)
    }

    setTouchpadNaturalScroll(val: boolean) {
        this._touchpadNaturalScroll = val
        this.applyAndSave("input:touchpad:natural_scroll", val ? 1 : 0)
    }

    setTouchpadTap(val: boolean) {
        this._touchpadTap = val
        this.applyAndSave("input:touchpad:tap_to_click", val ? 1 : 0)
    }

    setNumlockOnBoot(val: boolean) {
        this._numlockOnBoot = val
        this.applyAndSave("input:numlock_by_default", val ? 1 : 0)
    }

    setKbRepeatDelay(val: number) {
        this._kbRepeatDelay = Math.round(val)
        this.applyAndSave("input:repeat_delay", this._kbRepeatDelay)
    }

    setKbRepeatRate(val: number) {
        this._kbRepeatRate = Math.round(val)
        this.applyAndSave("input:repeat_rate", this._kbRepeatRate)
    }

    setKbLayout(layout: string, variant = "") {
        this._kbLayout = layout
        this._kbVariant = variant
        hs.evalLua(`hl.config({ input = { kb_layout = "${layout}", kb_variant = "${variant}" } })`)
        this.applyAndSave("input:kb_layout", layout)
    }
}

const inputConfig = new InputConfig()
export default inputConfig
