import GObject from "gi://GObject"
import GLib from "gi://GLib"
import hs from "./HyprlandState"

interface MonitorState {
    scale: number
    transform: number
    /** Explicit mode "WxH@Hz"; undefined → "preferred". */
    mode?: string
}

class MonitorConfig extends GObject.Object {
    static {
        GObject.registerClass({ GTypeName: "MonitorConfigManager" }, this)
    }

    private state: Map<string, MonitorState> = new Map()
    private _vrr = 0

    constructor() {
        super()
        // Re-read the effective vrr if Hyprland reloads its config (e.g. the user
        // edits hyprland-user.lua). Otherwise the next _save() would persist our
        // stale _vrr back into nidara-monitor.lua, clobbering the external change.
        hs.connect("config-reloaded", () => { this._vrr = hs.getOptionInt("misc:vrr") })
    }

    /** Call once with the monitor list from AstalHyprland.get_monitors() */
    init(monitors: Array<{ name: string; scale?: number; transform?: number; vrr?: number }>) {
        this.state.clear()
        for (const mon of monitors) {
            this.state.set(mon.name, {
                scale: Math.round((mon.scale ?? 1.0) * 100) / 100,
                transform: mon.transform ?? 0,
            })
        }
        // misc:vrr is a GLOBAL int (0=off, 1=always, 2=fullscreen-only). AstalHyprland's
        // Monitor.vrr is just a per-monitor bool and doesn't reflect it, so read the real
        // effective value via HyprlandState (otherwise it resets to off on UI reload).
        this._vrr = hs.getOptionInt("misc:vrr")
    }

    getScale(name: string) { return this.state.get(name)?.scale ?? 1.0 }
    getTransform(name: string) { return this.state.get(name)?.transform ?? 0 }
    getMode(name: string) { return this.state.get(name)?.mode }
    get vrr() { return this._vrr }

    private _apply(name: string, cfg: MonitorState) {
        // This config uses Hyprland's Lua parser, where `hyprctl keyword` is rejected
        // ("can't work with non-legacy parsers. Use eval."). Apply via eval
        // running the same hl.monitor() call the persisted .lua uses.
        const mode = cfg.mode ?? "preferred"
        hs.evalLua(`hl.monitor({ output = '${name}', mode = '${mode}', position = 'auto', scale = ${cfg.scale}, transform = ${cfg.transform} })`)
    }

    setScale(name: string, scale: number) {
        const cfg = this.state.get(name) ?? { scale: 1.0, transform: 0 }
        cfg.scale = scale
        this.state.set(name, cfg)
        this._apply(name, cfg)
        this._save()
    }

    setTransform(name: string, transform: number) {
        const cfg = this.state.get(name) ?? { scale: 1.0, transform: 0 }
        cfg.transform = transform
        this.state.set(name, cfg)
        this._apply(name, cfg)
        this._save()
    }

    /** Apply a resolution/refresh mode WITHOUT persisting — pair with commit() once
     *  the user confirms (so a bad mode can be reverted without touching the .lua). */
    applyMode(name: string, mode: string) {
        const cfg = this.state.get(name) ?? { scale: 1.0, transform: 0 }
        cfg.mode = mode
        this.state.set(name, cfg)
        this._apply(name, cfg)
    }

    /** Apply a rotation WITHOUT persisting — pair with commit() (revert-safe). */
    applyTransform(name: string, transform: number) {
        const cfg = this.state.get(name) ?? { scale: 1.0, transform: 0 }
        cfg.transform = transform
        this.state.set(name, cfg)
        this._apply(name, cfg)
    }

    /** Persist the current in-memory state to nidara-monitor.lua. */
    commit() { this._save() }

    setVrr(val: number) {
        this._vrr = val
        hs.evalLua(`hl.config({ misc = { vrr = ${val} } })`)
        this._save()
    }

    private _save() {
        const lines: string[] = [
            "-- NIDARA SHELL MONITOR SETTINGS",
            "-- Auto-generated by Nidara Settings UI. Do not edit manually.",
            "",
        ]

        for (const [name, cfg] of this.state.entries()) {
            const mode = cfg.mode ?? "preferred"
            if (cfg.transform !== 0) {
                lines.push(`hl.monitor({ output = "${name}", mode = "${mode}", position = "auto", scale = ${cfg.scale}, transform = ${cfg.transform} })`)
            } else {
                lines.push(`hl.monitor({ output = "${name}", mode = "${mode}", position = "auto", scale = ${cfg.scale} })`)
            }
        }

        if (this._vrr !== 0) {
            lines.push("")
            lines.push(`hl.config({ misc = { vrr = ${this._vrr} } })`)
        }

        const configPath = GLib.build_filenamev([
            GLib.get_home_dir(), ".config", "nidara", "nidara-monitor.lua"
        ])
        try {
            const dir = GLib.path_get_dirname(configPath)
            if (!GLib.file_test(dir, GLib.FileTest.EXISTS)) {
                GLib.mkdir_with_parents(dir, 0o755)
            }
            GLib.file_set_contents(configPath, lines.join("\n") + "\n")
        } catch (e) {
            console.error("[MonitorConfig] Failed to write config:", e)
        }
    }
}

const monitorConfig = new MonitorConfig()
export default monitorConfig
